### ISSUE TITLE
Task: Define supabase response error code translated messages

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#101]
# Task Description

As it stands, errors returned by supabase queries contain english messages. [Supabase hasn't yet exhaustively documented associations between error codes and error messages](https://github.com/supabase/supabase/discussions/3873), but there is documentation for PostgREST-related errors: https://postgrest.org/en/latest/errors.html

Every response from supabase should pass through a basic `{object} as const` or map lookup step to get a customized and translated message associated with the error's code.

# List of actions

- [ ] Establish if lookup should be static or if might need to include arguents to be concatenated with the message string (ex including user name in message, including returned time, etc.)
- [ ] Define error codes and their equivalent french messages in [keys.ts](https://github.com/CUPUM/nplex/blob/main/frontend/src/utils/values/keys.ts) or elsewhere.
- [ ] Make sure every message-dispatching error uses this reference to lookup for translated messages before dispatching
