### ISSUE TITLE
Task: Create a retrospective and prospective state-of-the-project

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#105]
# Task Description

For follow-ups within and outside the chair, we need an exhaustive _state-of-the-project_ or _work-in-progress_ document that establishes clearly the past processes and tasks (what was done), the current state, and the work planned on the road ahead.

# List of actions

- [x] Action: Determine format
- [ ] Action: Document past work
- [ ] Action: Document current state
- [ ] Action: Document future work
