### ISSUE TITLE
Task: Switch style system to Vanilla extract for static-typing and easier helpers implementations

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#106]
# Task Description
Describe this task here

# List of actions
- [ ] Setup vanilla-extract and vite-plugin
- [ ] Transfer main theme(s)
  - [ ] Establish darkmode theme for testing purposes
- [ ] Transfer component styles

**Comment by iolyd** [comment]
Closing as this approach was rejected for introducing unwarranted complexity and breaking away from svelte's own handling of `style:` or `class:` props.
