### ISSUE TITLE
Task: Implement server-side image processing and create web image component

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#108]
# Task Description

## Image processing (server-side)

Images uploaded by users should be processed by the server on upload, before being sent to supabase's storage. This allows deriving a modern web format (`webp`, `srcset`, etc.) from input standard image formats (`.jpg`, `.png`, etc.).

The go-to package for handling this on node servers seems to be [Sharp](https://www.npmjs.com/package/sharp). This would also allow us to consistently extract dominant colors form submitted images (https://github.com/lovell/sharp/issues/640), something that could enable relevant features #115 

## Image component

Conversly, an `<Image ... />` primitive component should be implemented to handle the retrieved web-image data. This component should:

- Implement lazy-loading (using intersection?)
- Accept either standard src or srcset, with respective handling and templating
- Accept external styling (classes, style)
- Forward events
- Provide customizable placeholder / loading (slot?)
- Include expected a11y props

# List of actions

- [x] Kickstart supabase storage system
- [x] ~~Implment sharp handling on image upload~~
- [x] Review storage and sharp processing to group images as source sets (adding an additional directory level)
- [ ] Create Image component

**Comment by iolyd** [comment]
The source-set generation approach has been revised for a more framework-idiomatic one where a single large resolution webp image is uploaded to the storage and variant sizes are generated on demand with an endpoint. Its overall performance will be tested during the next days/weeks, but this should prove to be more versatile.

(See https://github.com/CUPUM/nplex/blob/main/frontend/src/routes/api/image/%5Bbucket%5D/%5B...path%5D/%2Bserver.ts for ref.)

**Comment by iolyd** [comment]
Without proper caching, using an in-house svelte-kit endpoint to transform images is rather inefficient and could lead to high cpu-usage costs.
Unless responsive or resized images become crucial, we should wait until Supabase's resize API drops (https://github.com/supabase/supabase/discussions/1407) instead of trying to handle multiple storage objects for each uploaded image.
