### ISSUE TITLE
Task: VdeM - Demande de prolongation

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#112]
# Task Description

Les documents de la demande à l'origine de la convention sont disponibles ici: https://cirrus.gnp.umontreal.ca/index.php/f/405871 (Voir page 7 de la proposition de projet pour échéancier à réviser.)

# Actions

- [x] Réviser l'échéancier de la demande initiale
- [x] Faire approuver par SK
- [x] Faire suivi auprès de JD

**Comment by iolyd** [comment]
@sjinko Voici une version de la présentation du projet avec un échéancier ajusté (page 7): https://cirrus.gnp.umontreal.ca/index.php/f/465803
