### ISSUE TITLE
Epic: Créer une documentation technique de Nplex

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#119]
### Epic Description

As the project's development moves forward, certain architectures, certain schema and their specificities (constraints, triggers, etc), as well as some out-of-package-management dependencies, become key elements to understand how the platform works.

To ensure the project's maintainability and accessibility to developpers other than @iolyd , a concise documentation must be provided.

#### Key points to document

- [ ] Package.json scripts
- [ ] Core dependencies
- [ ] Full-stack architecture (in no particular order)
  - [ ] Authentication
  - [ ] Frontend
    - [ ] I18n helpers
  - [ ] CRUD
    - [ ] Superforms
  - [ ] Styles
    - [ ] PostCSS setup
    - [ ] Dark/light mode
    - [ ] Global stylesheets
  - [ ] Database
    - [ ] Schema
    - [ ] Authorization
    - [ ] I18n handling

### Tasks

- [ ] #105

**Comment by iolyd** [comment]
Refer to #289 instead
