### ISSUE TITLE
Task: Assign nplex issues to nplex project

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#120]
# Task description:
Associer chaque issue à un projet
[Liste des projets de la chaire sur la page d’accueil](https://github.com/orgs/CUPUM/projects)

# List of action:
 - [x] Action: Lister ci-bas en commentaire les projets dont j’ai la gestion dans la liste des projets de la chaire
 - [x] Action: Si un projet sur lequel je travaille n’apparait pas créer un nouveau projet **beta**
 - [x] Action: Ajouter les projets sur lesquels je travaille au repo concerné (où se trouvent la plupart des issues et les documents associés)
 - [ ] Action: Brièvement décrire le projet et qui sont les responsables dans l’onglet associé (à droite) 
 - [x] Action: Dans chaque projet, ajouter les issues concernées (ce issue doit-il être régler pour terminer le projet)

**Comment by iolyd** [comment]
Projet nplex: https://github.com/orgs/CUPUM/projects/23

**Comment by iolyd** [comment]
The repo's readme serves as the project description. This task is considered completed.
