### ISSUE TITLE
Task: Move session retrieval to server routes/layouts 

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#124]
# Task Description
User session should ve retrieved in `+layout server.ts` rather than non-server routes/layouts

# List of actions
- [x] Move root session retrieval to server
- [x] Fix bugs it introduces with signin redirect
- [x] Fix bugs it introduces in invalidated nested layouts/routes
