### ISSUE TITLE
Task: Chose definitive hosting service and complete setup

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#130]
# Task Description

Establish if nplex's frontend should be hosted on Railway or Vercel. Is there already an org. account at vercel for the aggregator?

### Freemiums

Railway free hosting has a limit of 500 hrs per month (about 20 days) for continuous up-time. Vercel's free package does not seem to have up-time limits, but instead appears to shut off instances after a set timer and only re-boots them on the next query, leading to a ~30 sec delay on said first re-visit.

### Paid

Both services have similar features, Railway being a more fully-fledged customizable hosting while Vercel offers a more turnkey format for frontend.

# List of actions

- [x] Compare both options
- [x] Re-deploy nplex to chosen service
- [x] Update main version form latest stable dev

**Comment by iolyd** [comment]
New deployment setup is now completed for Vercel, as of 662bf60
