### ISSUE TITLE
Task: Pay subscriptions to services (supabase & vercel) to unlock premium features

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#137]
# Task Description

The platform currently runs on freemium plans both at the level of the hosted database (supabase) and the frontend build/host environments (vercel).

While we way not reach the limits of these free plans in terms of bandwidth, queries, uptime, etc., upgrading to payed plans will unlock key features.

## Supabase

Supabase's entry-level payed plan unlocks [continuous automatic database backups](https://supabase.com/docs/guides/platform/backups) and [image transformations](https://supabase.com/docs/guides/storage/image-transformations).

Upgrading would help us close #50.

## Vercel

For the time being, not as important as db upgrade.

# List of actions
- [ ] @iolyd: Establish payment management for Supabase
  - Project level _vs_ Org level (if possible)
- [ ] @sjinko: Proceed with payment
- [ ] @iolyd: Establish payment management for Vercel
   - Co-locate with https://github.com/CUPUM/svlc-monorepo inside org
   - Pay at org level vs project level, how are we constrained by funding rules.
 - [ ] @sjinko: Proceed with payment

**Comment by sjinko** [comment]
ça coute combien, et on doit payer pour combien de temps?

**Comment by iolyd** [comment]
@sjinko Pour Supbase c'est 25$/mois (https://supabase.com/pricing), on pourrait déterminer la durée d'abonnement en fonction des fonds de Nplex disponibles.

Pour Vercel, c'est 20$/mois/utilisateur (https://vercel.com/pricing). C'est une formule de paiement un peu spéciale... surtout si on se retrouve avec des utilisateurs qui ne l'utilise pas tant pour faire du développement (i.e. un compte utilisé uniquement pour faire les paiements). L'abonnement Vercel est moins pressant / essentiel dans le cas de Nplex. Je crois qu'il vaudrait d'établir avec @hugobb si on veut procéder avec une équipe commune, sachant qu'il y a probablement des contraintes administratives/budgétaires avec l'utilisation des fonds des deux projets.

**Comment by iolyd** [comment]
Je ferme ce issue car nous utilisons un nouveau stack de services. Un issue plus à jour sera créé en lien avec les nouveaux abonnements.
