### ISSUE TITLE
Task: Implement confirm/dialog system to prevent loss of unsaved data or add step to deletion of important ressources

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#138]
# Task Description

Currently, if a user navigates away from a page without saving the data, the navigation will proceed without warning nor caching of unsaved data resulting in losing it.

We could use a simple `localStorage` temporary saving mechanism, but that wouldn't ensure the data is then percolated to the database.

To give greater control and data-handling _awareness_ to the users, we should implement a confirm dialog component that can intervene in two ways:

- with a navigation highjack (`onBeforeNavigate`) based on a boolean key value.
- with a programmatic trigger (or other strategy?) to prevent form submission for cases such as entry deletions.

The component should expose 2 functions (`confirm`, `reject`) as slot props that could then be called from its slotted content.

# List of actions

- [x] Implement dialog
- [x] Implement navigation highjack
- [x] Implement onbeforeunload browser highjack?
- [x] Test with project form using `$dirty` as the key.
- [x] Apply wherever needed

**Comment by iolyd** [comment]
This feature is now implemented through the `Dialog` and `NavigationConfirmDialog` components. It is showcased in the project editor form and will  form now on be applied elsewhere whenever relevant.
