### ISSUE TITLE
Epic: Adopt db-level roles instead of typed roles

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#140]
# Epic Description

To unlock CLS and a more robust RBAC implementation, we should transition to postgres roles. Read https://github.com/supabase/supabase/discussions/11948 for info. There is an ongoing pr to add role management inside the UI, but we can engage the transition prior.

# List of Tasks (Complete in order)

- [ ] Create roles
- [ ] Connect (grant rights) to `authenticator` role
- [ ] Update functions + RLS
- [ ] Reset table column rights (`revoke update ...`) and grant what is needed on a role-per-role basis
- [ ] Implement server-side role update logic using service key to update `auth.users(role)`

**Comment by iolyd** [comment]
This update can wait and _should_ wait for a cleaner handling of db roles on Supabase's side (see linked discussion and its unmerged PRs)

**Comment by iolyd** [comment]
This work is to be reviewed depending on #165 as database requests management would be drastically different than it currently is.
