### ISSUE TITLE
Task: Renew `nplex.design` domain

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#159]
# Task Description

Last summer, @iolyd bought a custom domain for facilitating publicly sharing the app. The 1yr contract comes to a close within the next month and we should determine if we want to keep the domain or not. If we opt to keep the domain `nplex.design`, we should transfer its ownership to the chair for managing payments accordingly.

Additionnally, after checking, it appears [namecheap](https://www.namecheap.com/) jacked the domain's renewal price to 60$, which is ridiculous. We should look into transfering the domain to a different registrar with better pricing ethics.

# List of actions

- [x] Look for new provider to transfer away from namecheap
- [x] Confirm we want to stay with the same domain
- [x] Verify if there is a way to transfer a contract or domain ownership
- [x] Renew domain
- [x] Store order-related documents

**Comment by iolyd** [comment]
@sjinko, j'ai renouvelé l'abonnement avec succès enfin. Où serait le meilleur endroit pour conserver la facture, `general` ou `nplex-organisation` ?

**Comment by sjinko** [comment]
Les deux. dans général, tu peux le mettre dans providers/
________________________________
