### ISSUE TITLE
Task: Présenter en bonne et due forme sur le site la participation de la VdeM (logos, mentions, etc.)

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#160]
# Task Description

La convention établie avec la Ville de Montréal prescrit d'intégrer des logos et mentions spécifiques au site et aux communications liées au projet.

Pour plus de détails, consulter le point `4.4` de la [Convention signée avec la Ville](https://github.com/CUPUM/subventions/blob/main/20210414-designmontreal/montreal-convention-nplex_signed-20210809.pdf) (page 4) et le **Protocole de visibilité** (page 14, mais révisé depuis..?) :

> **4.4 Promotion et publicité**
> 
>   4.4.1
>   faire état de la participation financière de la Ville et de celle du MCC, conformément aux dispositions concernant le Protocole de visibilité (ciaprès le « Protocole de visibilité ») joint à la présente Convention à l’Annexe 2 et apposer la signature « Montréal Ville UNESCO de design » dans tout document, communication, activité, publicité, affichage, rapport de recherche ou document d’information, quel qu’en soit le support, relatif à l’objet de la présente Convention et faire en sorte que ces documents reflètent, de façon équitable, l’importance de l’aide accordée par la Ville et par le MCC par rapport aux autres personnes qui auraient contribué au Projet. Tout écrit relatif au Projet doit être approuvé par le Responsable et par le MCC avant diffusion;

Avant de procéder à quelconque diffusion publique, nous devons nous assurer de bien ajouter ces éléments et de faire approuver leur intégration par une personne ressource au niveau de la Ville.

# List of actions

- [x] Récupérer les logos
- [x] Re-designer le footer du site pour y inclure le(s) logo(s) requis
- [x] Demander des versions supplémentaires:
  - [x] Format SVG
  - [x] Français ET anglais
  - [x] version "inversable"
- [x] Faire approuver une première version (demande envoyée, en attente de traitement)

**Comment by sjinko** [comment]
Salut Sarah, pourrais-tu nous décrire ce qui doit être fait pour respecter le protocole de visibilité de la ville. L’info est en annexe de la convention.

**Comment by iolyd** [comment]
Nous avons reçu l'approbation et quelques précisions en réponse à des questions que j'avais partagé:

> Bonjour,
> 
> Désolé pour le délai de réponse, c'est approuvé pour le visuel envoyé.
> 
> Vous trouverez en pièce jointe notre trousse complète de logos, avec la version inversée (blanc sur noir).
> 
> Je n'ai pas le format SVG, si besoin je pourrais faire une demande à mes collègues graphistes, faites-moi signe si nécessaire.
> 
> Enfin, il n'y a qu'une seul version du logo, il faut utiliser la version française même en anglais svp. 
> 
> Merci pour cette visibilité!
> 
> Cordialement,
> Alice Reliaud
