### ISSUE TITLE
Task: Clarifier la portée de l'API du portail de données Montréal

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#161]
# Task Description

Certains jeux de données affichés sur [le portail des données ouvertes de la Ville de Montréal](https://donnees.montreal.ca/dataset) peuvent être récupérés via un API. Par exemple, voir le bouton `API` ici: https://donnees.montreal.ca/dataset/permis-construction/resource/00c4f698-7162-45f8-8c3e-33ccaed139d5.

Selon l'information écrite, l'API s'appui sur [CKAN + DataStore](https://docs.ckan.org/en/latest/maintaining/datastore.html). Avant de continuer notre démarche avec une demande d'accès privilégié à des services de données auprès de la Ville, nous devrions explorer les requêtes possibles avec les endpoints publics, par exemple:

- Pouvons nous faire des recherches avec des critères basés sur la valeur de certaines colonnes (`select ... where ...`)
- Si oui, quels opérateurs comparatifs sont admis? `=`, `>`, `<->` (proximité), etc.
- Pour des jeux de données avec des colonnes de coordonnées géographiques (probablement avec le format `[lng, lat]`, ou avec format `Geometry` de PostGIS?), nous est-il possible d'utiliser ces données pour filtrer les résultats de requête?

Lien du google colab -  [API du portail de données de la ville de Montréal](https://colab.research.google.com/drive/1LfGOmRRWr8GvYRwnUOiwkYIoaRS9-Q4t?usp=sharing)

Lien du google colab -  [API du portail de données ouverte du Canada](https://colab.research.google.com/drive/1YjHNcDi5MWqu4mI62PEtihDSgYFDWMkN#scrollTo=C9Fyc5XF3cLK)

# List of actions
- [x] Explorer la documentation de CKAN + DataStore
- [x] Résumer les types de requêtes possibles
- [x] Tester différents niveaux de spécificité ou différentes combinaisons d'opérateurs en créant des requêtes (avec Postman ou un autre client REST)
- [x] Tester temps pour une requête - entrées d'une année complète
- [ ] Explorer les données ouvertes - niveau [Canada](https://ouvert.canada.ca/fr/donnees-ouvertes)

**Comment by iolyd** [comment]
Salut @frroye, quand serait un bon moment pour toi pour une petite rencontre d'introduction au projet et à ce issue?

**Comment by frroye** [comment]
Salut @iolyd  je suis dispo maintenant ou n'importe quand aujourd'hui!

**Comment by frroye** [comment]
Salut @iolyd , je te fais un petit update pour valider que j'ai bien compris et te tenir au courant! 

- J'ai exploré les fonctionnalités de postman : ça permet d’organiser des requêtes en les regroupant en ‘’collections’’, d’associer les requêtes avec des environnements dans lesquels on peut définir des variables, etc. et l’interface est pratique pour voir la réponse de la requête. Par contre, j’ai quand même fait un Google Colab parce que ça permet de commenter chaque requête plus facilement (je trouve!). 

- Les requêtes sql ont l’air de fonctionner ‘’normalement’’ : c’est possible de filtrer selon les colonnes avec le WHERE. J’ai testé aussi le GROUP BY, ORDER BY, les fonctions d’agrégation (AVG, SUM, etc.). C’est possible de faire des requêtes sur plusieurs datasets en même temps, d’utiliser les JOIN, etc. 

- Je ne suis pas certaine de quels sont nos privilèges exactement mais sans surprise on ne peut pas créer de nouvelles tables ou modifier des tables existantes. Certaines requêtes m’ont aussi renvoyé des messages du type : "Accès non autorisé: {'permissions': ['Not authorized to access system tables']}", par exemple quand je voulais voir si postgis était installé. 

- Postgis ne semble pas installé, mais c’est possible de filtrer spatialement certains datasets soit avec les champs arrondissement ou code d’arrondissement, ou avec les champs LOC_X et LOC_Y, qui sont des coordonnées en EPSG:2950 (en mètres), comme je le montre dans la section filtrage spatial du premier dataset. 


Tu peux commenter ou modifier le google colab et/ou on peut se parler pour que je te le présente! Est-ce qu’il y a certains éléments que je devrais plus creuser? Sinon je pensais aller explorer du côté de données Québec.

lien: https://colab.research.google.com/drive/1LfGOmRRWr8GvYRwnUOiwkYIoaRS9-Q4t?usp=sharing

**Comment by iolyd** [comment]
Salut @frroye. Super, ça répond à plusieurs questions! Ça serait effectivement une bonne idée de prévoir une rencontre pour me présenter le google colab. Prévois-tu être à l'école demain ou mardi?

Et oui, je dirais que c'est une exploration assez approfondie pour l'instant et c'est une bonne idée de regarder ce qui serait possible au niveau des autres services de données. Je crois comprendre que Données Québec s'appuie aussi sur CKAN, mais je ne sais pas si c'est le cas au niveau du Canada.

- [Québec](https://www.donneesquebec.ca/)
- [Canada](https://ouvert.canada.ca/fr/donnees-ouvertes)

**Comment by frroye** [comment]
Ça marche pour mardi après le café-rencontre de groupe ou en pm (demain je ne vais pas être là).

**Comment by frroye** [comment]
Salut @iolyd,

J'ai ajouté une section dans le google colab de l'API pour Montréal avec des tests de temps de requêtes. Par exemple, pour le dataset des permis de construction, pour l'année 2021 au complet, on parle d'environ 6 secondes; en filtrant spatialement (cercle de 500m autour de la station Jean-Talon) c'est plus autour de 2s, et environ 1 seconde pour l'arrondissement Outremont, Ville-Marie ou Sud-Ouest. 

Concernant l'api des données ouvertes du Canada, elle est aussi basée sur CKAN et l'extension DataStore, donc il est aussi possible de faire de requêtes SQL sur les datasets. Par contre, l'api est activée pour seulement 262 des 37561 dossiers de données ouvertes, et je ne suis vraiment pas certaine quels jeux de données seraient intéressants parmi ceux dont l'API est activée. Sur les 1278 dossiers disponibles en format geojson, aucun n'est accessible via l'API.

**Comment by iolyd** [comment]
@frroye super, merci! Pour la suite, je crois qu'on pourrait commencer à se lancer progressivement dans le développement axé sur l'application avec SvelteKit. Je vais créer un issue où on pourra organiser ton apprentissage du _framework_ et ensuite la stratégie d'intégration dans l'application.

**Comment by frroye** [comment]
@iolyd c'est ok si je ferme celle là? Ou bien il y a d'autres exploration à faire éventuellement?

**Comment by iolyd** [comment]
C'est bon, je ferme, à réouvrir si jamais on se relance dans l'utilisation de ces données dans le futur.
