### ISSUE TITLE
Task: Établir échéancier très stricte et précis pour jusqu'au 1er septembre

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#166]
# Task Description

Prioriser NPLEX!

**Outline préliminaire des chantiers**

- Collecte des données (projets)
- Complétion frontend
- Complétion database (schema)
- Prévision / organisation campagne de communication

# List of actions
- [x] Établir mode de gestion des échéances -> Milestones
- [x] Créer les milestones et spécifier des dates d'échances
- [ ] Attribuer chaque issue existant à un milestone d'intérêt (dans la mesure du possible si applicable, autrement valider la pertinence du issue ou s'il manque des milestones)
- [ ] Créer de nouveaux issues et les assigner à des milestones pour détailler autant que possible les prochaines étapes du projet

**Comment by iolyd** [comment]
Out of date
