### ISSUE TITLE
Task: Prendre contact avec les firmes

### ISSUE THREAD

**Issue by frroye** [CUPUM/nplex#181]
# Task description:
Prendre contact avec des firmes d'architecture de Montréal pour leur proposer de populer la plateforme NPLEX (aim:25 organismes/bureaux)

Les bureaux devront être identifiés, contactés et relancés (avec parcimonie).

Il faut bien construire un argumentaire convainquant pour que les bureaux aient envie d’utiliser la plateforme : projet accompagné par la ville de Montréal, visibilité auprès de citoyens et des arrondissements, à but non lucratif, aucune cessation des droits 

# List of tasks 

- [x] Action: Établir un calendrier de recrutement des firmes
- [x] Action: Identifier des stratégies de recrutement/de prise de contact
- [x] #184
- [x] #185
- [x] #186
- [x] #187
- [x] Action: Établir un responsable par firme (diviser la liste en 3) (pour le 5 septembre)
- [x] #188
- [x] #190
- [x] #189
- [x] Action: Relancer les firmes (18 septembre) - courriel
- [x] Action: Faire la liste des firmes intéressée (18 septembre)

**Comment by roxanekasprzyk** [comment]
Bonjour @sjinko, 

Peut-on envoyer un premier courriel aux firmes sans visuel de la plateforme ? 
ou penses tu que nous attendons un lien de la plateforme ou des captures d'écran pour leur présenter un exemple ? 

Merci à toi, 
Bonne fin de journée

**Comment by sjinko** [comment]
Je pense qu’il serait bien d’avoir au moins un visuel et le logo pour bien leur « vendre » la plateforme.
