### ISSUE TITLE
Task: Planifier les invitations

### ISSUE THREAD

**Issue by roxanekasprzyk** [CUPUM/nplex#191]
# Task: Planifier les invitations
Planifier les invitations à l'évènement. 
On prévoit environ 60 invités. 

- Firmes d'architectures (environ 20 firmes, 2 personnes par fimes): 40-50 personnes
- Chaire Unesco : 10 personnes
- Ville de Montréal : 2 personnes
- Faculté de l'aménagement : 5 personnes max

# List of tasks 

- [x] Action: Rédiger une lettre d'invitation pour les firmes
- [x] #204
- [x] #205
- [x] #206
- [x] #207
- [ ] Action: Imprimer une liste des personnes invitées
- [ ] Action: Prévoir des portes-noms ou étiquettes

**Comment by frroye** [comment]
Première version du [mail d'invitation pour les firmes](https://github.com/CUPUM/nplex-organisation/blob/aca3dc7666f1752fdd60677cd0f36038a58db9aa/partenariats/kasprzyk_roy_tannir-courriel-invitation_lancement-20230925.docx) à valider/ajuster @roxanekasprzyk .

**Comment by SarahTannir** [comment]
![tannir-visuel_lancement_nplex-20230927](https://github.com/CUPUM/nplex/assets/99455471/5511e7f2-feee-4e6c-985d-6e8eb02af434)

**Comment by SarahTannir** [comment]
![tannir-visuel_nplex_lancement-20230927](https://github.com/CUPUM/nplex/assets/99455471/cecd1f70-39a5-4bc7-8408-1dd3b0941b4a)
@roxanekasprzyk

**Comment by roxanekasprzyk** [comment]
Salut @sjinko 

Voici la [la lettre d'invitation](https://github.com/CUPUM/nplex-organisation/blob/main/partenariats/kasprzyk_roy_tannir-courriel-invitation_lancement-20230925.docx) pour les firmes d'architecture. Nous proposons de rajouter un petit visuel "phare" pour mettre en évidence la date, l'heure, le lieu de l'évènement et le logo de la plateforme. 
Nous pensons l'intégrer directement dans l'email, comme tu peux le voir sur la capture d'écran dans le message suivant. 
Qu'en penses tu ?

**Comment by roxanekasprzyk** [comment]
<img width="689" alt="image" src="https://github.com/CUPUM/nplex/assets/124221528/00e06d48-62ee-4db8-9d3f-fa4642856615">

**Comment by frroye** [comment]
[Drive pour la liste des invités](https://docs.google.com/spreadsheets/d/1lV4lQkXziavvMfSlFF2hDx212az6SMIbLkUlqJajRwA/edit?usp=sharing)
