### ISSUE TITLE
Task: Planifier le buffet

### ISSUE THREAD

**Issue by roxanekasprzyk** [CUPUM/nplex#192]
# Task description:
Planifier l'alcool et la nourriture servis durant l'évènement. 

# List of tasks 
- [x] Action: faire une liste de bouchers et d'alcool (via Local Local)
- [x] #202
- [x] Action: Commander le buffet à Local Local 
- [x] Action: Appeler Local Local pour le suivi

**Comment by SarahTannir** [comment]
Pour référence: 
<img width="201" alt="Screenshot 2023-09-27 at 12 04 56 PM" src="https://github.com/CUPUM/nplex/assets/99455471/b82a6a4c-cb0b-4263-940a-8a10e102ea9b">

**Comment by roxanekasprzyk** [comment]
Salut @sjinko 

Voici la liste [Excel buffet ](https://github.com/CUPUM/nplex-organisation/blob/main/kasprzyk-liste-buffet_excel-20230927.xlsx) que nous proposons pour le buffet de l'évènement, nous l'avons fait sans contrainte de budget, c'est une première proposition. 
Il y a également la capture du panier de Local Local dans le message de Sarah juste au dessus

**Comment by sjinko** [comment]
Il me semble que 80 bouchées pour 60 personnes est trop peu. Il faudrait au moins 2 bouchées par personnes, et prévoir au moins une consommation d’alcool et une consommation d’eau par personne.

Les plateaux (crudités et fromage) me semble très cher par personne. Je me demande si on n’a pas meilleurs temps de ne prendre que des bouchées. Il faut compter qu’en général, seulement 50% à 80% des gens invitées viennent.

**Comment by SarahTannir** [comment]
<img width="182" alt="Screenshot 2023-09-28 at 4 33 14 PM" src="https://github.com/CUPUM/nplex/assets/99455471/8d40e8e6-49b7-42c7-87b7-1ae65bc225f2">
<img width="187" alt="Screenshot 2023-09-28 at 4 33 25 PM" src="https://github.com/CUPUM/nplex/assets/99455471/eda24c94-a60a-4fd5-926f-52a4b72163f6">

**Comment by sjinko** [comment]
Ok, pour la liste des invites, il faudrait s’assurer d’inviter les membres du comité conseil et les bureaux partenaires. Voir avec Emmanuel ***@***.***)
________________________________

**Comment by SarahTannir** [comment]
Noted @sjinko ! Une autre question, comment on fait pour payer local local (voir ci-dessus)?

**Comment by sjinko** [comment]
Il suffit d’indiquer sur le formulaire que c’est pour Shin Koseki de l’Ecole d’urbanisme. Le paiement se fait après sur facture interne.
________________________________
