### ISSUE TITLE
Task: Planifier la salle de l'évènement

### ISSUE THREAD

**Issue by roxanekasprzyk** [CUPUM/nplex#193]
# Task description:
Définir le lieu de l'évènement et s'occuper des réservations. 

# List of tasks 
- [x] Action: Contacter Isabelle Couillard 
- [x] Action: Contacter DI Local 
- [x] #199
- [ ] ~~#200~~
- [ ] ~~Action: Faire une [demande de permis de réunion](https://www.racj.gouv.qc.ca/formulaires-et-publications/formulaires/alcool/reunions.html)~~
- [x] #198

**Comment by frroye** [comment]
@SarahTannir Pour la demande de permis de réunion, il faut un "Contrat de location ou déclaration du propriétaire" de la salle, est-ce que on a un contrat/document qui confirme la réservation du hall? 
<img width="578" alt="image" src="https://github.com/CUPUM/nplex/assets/50641609/93fc21a6-60d2-49a9-b5e1-c6ce81fe67d5">

**Comment by SarahTannir** [comment]
> @SarahTannir Pour la demande de permis de réunion, il faut un "Contrat de location ou déclaration du propriétaire" de la salle, est-ce que on a un contrat/document qui confirme la réservation du hall? <img alt="image" width="578" src="https://user-images.githubusercontent.com/50641609/270017785-93fc21a6-60d2-49a9-b5e1-c6ce81fe67d5.png">

Envoyé par courriel!
