### ISSUE TITLE
Task: Lister les indicateurs d'exemplarité et leur description

### ISSUE THREAD

**Issue by frroye** [CUPUM/nplex#209]
# Task description: 
Lister les indicateurs d'exemplarité et leur description. 

# List of tasks:
- [x] Action: Lister les [indicateurs d'exemplarité](https://docs.google.com/spreadsheets/d/1Las36Woy083nZUx7BPSz2H21zOmUp5HfhDWsSpLt87c/edit?usp=sharing)
- [ ] Action: Extraire les indicateurs d'exemplarité des descriptions des fiches projets, ajouter ceux manquants à la liste
- [x] Action: Ajouter leur description
- [x] Action: Traduire en anglais

**Comment by frroye** [comment]
Salut @iolyd! Je pense qu'il y a un petit bug pour la saisi des descripteurs: 

Quand je modifie l'indicateur d'exemplarité à la position i de la catégorie A, tous les indicateurs à la position i des autres catégories sont modifés aussi.
<img width="416" alt="image" src="https://github.com/CUPUM/nplex/assets/50641609/9bff2575-702d-4fb0-ab68-63838c22aa83">

Laisse moi savoir si tu as le temps de regarder ça!

SINON une solution rapide: puisqu'on a rentré les indicateurs, leur description et leur traduction dans un excel, je pourrais aller les mettre directement dans la base de données (updater project_exemplarity_indicators et project_exemplarity_indicators_t) avec un mini script python/google collab? Je pourrais faire un test sur la db dev? La seule question que j'aurais c'est la "forme" des ids (ex: bnTg0w): si je devais génerer des ids pour les indicateurs, est-ce qu'il y a des contraintes? Selon la lib que tu as utilisé?

**Comment by iolyd** [comment]
@frroye, ok je vais investiguer voir si c'est pas une omission simple. As-tu observé le même problème ailleurs?

**Comment by iolyd** [comment]
@frroye j'ai un fix, ça sera déployé d'ici 5 minutes

**Comment by frroye** [comment]
Yess merci! :)

**Comment by frroye** [comment]
Salut @iolyd j'ai rentré quelques indicateurs sans problèmes, mais là j'ai des erreurs de 

> POST https://www.nplex.design/edit/projects/descriptors/indicators?/update 504 (Gateway Timeout)

quand j'essaie d'enregistrer les changements. Je ne sais pas trop si c'est de "mon" côté ou de celui du serveur?

**Comment by iolyd** [comment]
@frroye C'est noté, je vais étudier les logs pour essayer de trouver la source.

**Comment by iolyd** [comment]
Salut @frroye, je crois avoir identifié d'où l'erreur vient, mais c'est au niveau de la _lib_ utilisée pour la validation et le bug ne fait que suspendre indéfiniment la requête sans log ni erreur. Je ne sais pas trop comment  résoudre cela, je vais ouvrir un issue sur le repo de la lib et envoyer une question sur leur forum.

**Comment by frroye** [comment]
@SarahTannir
