### ISSUE TITLE
Task: Préparer une affiche d’accueil 

### ISSUE THREAD

**Issue by SarahTannir** [CUPUM/nplex#215]
# Task Description
Affiche d'accueil pour l'événement.

# List of actions
- [ ] Action: Préparer l'affiche (format a1)
- [ ] Action: Voir avec Isabelle pour le chevalet
- [ ] Action: Imprimer l'affiche le mardi matin (+ cartes)
