### ISSUE TITLE
Task: Implement toast messages

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#219]
# Task Description

Toast messages are essential to provide users with feedback when actions fail or succeed. Currently, the interface simply displays error boundaries without much information or interactivity.

Such messages also add the possibility to display additional notifications to users in various cases (e.g.: general announcements).

# List of actions

- [x] Design toast component
- [x] Implement toast dispatching
- [x] Install flash messages for integration with superforms (form action feedback)

**Comment by iolyd** [comment]
Basic `Toast` message component is currently in place, but the integration with server-initiated messages (flash-messages) remains. Completion of this is judged somewhat critical as for the moment users get no feedback after form submissions (except errors triggering error boundaries).
