### ISSUE TITLE
Epic: Obtenir les données des bureaux partenaires

### ISSUE THREAD

**Issue by sjinko** [CUPUM/nplex#229]
# Epic description

Obtenir des différents bureaux d’architecture déjà partenaires du projet qu’ils mette en ligne un minimum de 5 projets chacun, et de leur propre bureau comme fiche d’acteur

# List of tasks:

- [x] CUPUM/nplex-organisation#2
- [x] (Manque de temps, à fusionner avec les ateliers) CUPUM/nplex-organisation#9
- [ ] CUPUM/nplex-organisation#10
- [ ] CUPUM/nplex-organisation#16 
- [ ] Task: Répondre au questions et commentaires des bureaux partenaires
