### ISSUE TITLE
Task: Contacter de nouveaux bureaux partenaires

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#230]
# Task description

Pour nous aider à atteindre le nombre de fiche prescrit par les objectifs du projet auprès de la Ville de Montréal, il serait pertinent d'aller chercher la collaboration d'un plus grand nombre de bureaux partenaires.

# Actions

- [x] Identifier nouveaux partenaires potentiels
- [x] Rédiger appel à partenariat
- [x] Valider
- [x] Envoyer aux contacts

**Comment by iolyd** [comment]
Des partenaires supplémentaires ont été rejoint à l'automne 2023 pendant la collecte de données avec les auxiliaires.
