### ISSUE TITLE
Epic: Mettre en action une campagne de communication destinée aux non-professionnels

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#231]
# Epic Description

Comme le projet Nplex vise aussi la population générale, au delà des acteurs professionnels des disciplines de l'aménagement, nous mobilisons ici un éventail de canaux pour communiquer au grand public l'existence de la plateforme et souligner son utilité pour les milieux utilisateurs citoyens et étudiants.

# List of Tasks (Complete in order)

- [ ] Cadrer le message principal
- [ ] Établir un calendrier des communication pour assurer une présence soutenue pendant une certaine période de temps
- [ ] Rédiger une collection de messages promotionnels (format court)
- [ ] Préparer du contenu visuel adapté aux différents canaux de comm.
- [ ] Faire approuver le respect du protocole de visibilité de la VdeM dans le contenu préparer
