### ISSUE TITLE
Task: Configurer et exécuter la migration vers les nouveaux services AWS (S3 et Image Handler)

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#248]
# Task description

Le déploiement de la nouvelle version est bloqué par un incompatibilité entre notre nouvelle et ancienne structure d'utilisation des services AWS. Comme certains paramètres ne peuvent pas être révisés après création des buckets, la seule solution est de migrer vers une nouvelle instance.

# Actions

- [x] Initier nouveaux buckets (dev et prod)
- [x] Configurer les buckets pour les paramètres non transférés par l'ancien bucket
- [x] Inclure nouveaux buckets dans _policy_ de nplex (https://us-east-1.console.aws.amazon.com/iamv2/home?region=ca-central-1#/policies)
- [x] Initier nouveaux stacks pour image handler
- [x] Tester dev
- [x] Tester prod
- [x] Mettre à jour `.env` de prod sur vercel pour compléter migration
- [x] Déployer nouvelle version

**Comment by iolyd** [comment]
This is completed as of 1456c3469c8476bcdef11ef2304871c3dbda43a1, FINALLY!
