### ISSUE TITLE
Epic: Cleanup styles management 

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#249]
# Epic Description

Current system for styles management is a bit inconsistent, mixing stylesheets and componen-scoped styles without too much thought.

# List of Tasks

- [x] Task: Define custom selectors for styles
- [x] Task: review `base` css vars
- [x] Task: define clearly an approach for nesting and css var handling

**Comment by iolyd** [comment]
These concerns were mostly completed in commits between fb5aab222ae8f5196f7a48e6673ddb298048bdca and fb5aab222ae8f5196f7a48e6673ddb298048bdca. See www.nplex.design/docs/styles for some basic documentation and refer to https://github.com/CUPUM/nplex/tree/main/src/styles for implementations.
