### ISSUE TITLE
Task: Deprecate self-implemented i18n systems in favor of paraglide-js

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#250]
# Task Description

For better code organization, perennity, and simpler maintenance, we should fully switch frontend translations management to inlang's newly released paraglide-js. It solves ICU message formatting, message extraction/generation from json sources, and more.

This is somewhat a low hanging fruit as a full setup has been tested and confirmed in a skeleton project.

# List of actions
- [ ] In terms of semantics, use `lang` rather than `locale` for clarity (even if not necessarily as concise)
- [x] Deprecate in-house locale constants and helpers where paraglide offers generated alternatives
- [ ] Replace all uses of `createTranslations` with message functions
- [x] Co-locate ALL messages in respective `messages/(lang).json` source files.
- [ ] Improve code clarity and organization for handle hook, layout data, and etc.
