### ISSUE TITLE
Task: Rédiger contenu de la page À propos

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#253]
# Task description
Texte de 300 à 500 mots qui présente nplex, son fonctionnement et qui remercie les soutiens financiers et les collaborateurs.

Rédiger le contenu de base dans la branche contenu

Voir content/apropos_fr.md, branche contenu.
Voir content/apropos_en.md, branche contenu.

# List of actions:
- [x] Action: Faire un projet draft de la section a propos en français
- [x] Action: Demander à @sjinko de revoir le draft
- [x] Action: Revoir le texte
- [x] Action: Traduire vers l‘anglais
- [ ] Demander à @sjinko de valider la traduction

**Comment by sjinko** [comment]
Parfait
