### ISSUE TITLE
Task: Rédiger le contenu de la section galerie de l'éditeur de projet

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#256]
# Task description
La section _Galerie_ de l'éditeur de projet a besoin de texte pour introduire ses fonctionnalités auprès des utilisateurs.
Ex: Constituez une gallérie pour votre projet! qu‘est-ce que les utilisateurs doivent mettre de l‘avant dans la galerie. Motivation et conseils aux utilisateurs 

Max. 300 mots

**Voir content/galerie_fr.md et content/galerie_en.md **

# Actions
- [x] Action: Rédiger texte d’introduction de la section galerie en français (300 mots)
- [x] Action: Demander à @sjinko de relire le contenu
- [x] Action: Faire les ajustements au texte
- [x] Action: Traduire le texte vers l’anglais
- [x] Action: Demander à @sjinko de valider la traduction

**Comment by sjinko** [comment]
Parfait
