### ISSUE TITLE
Task: Rédiger le contenu de la section général de l'éditeur de projet

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#257]
# Task description
Rédiger le texte d’introduction et des sous-section présentés aux utilisateurs dans l’éditeur de projet.

Pour chaque section, expliquer pourquoi nous demandons ces informations, comment elles seront utilisées, et comment l’utilisateur peut les renseigner

**voir content/editeur_fr.md, branche contenu.**
**voir content/editeur_en.md, branche contenu.**

# List of actions:
- [x] Action: Rédiger la version française du texte d’introduction (200 mots)
- [x] Action: Rédiger la version anglaise du texte d’introduction (200 mots)
- [x] Action: Rédiger la version française qui explique le type de projets (50 mots)
- [x] Action: Rédiger la version anglaise qui explique le type de projets (50 mots)
- [x] Action: Rédiger la version française qui explique les interventions (50 mots)
- [x] Action: Rédiger la version anglaise qui explique les interventions (50 mots)
- [x] Action: Rédiger la version française qui explique le type de propriétaire (50 mots)
- [x] Action: Rédiger la version anglaise qui explique le type de propriétaire (50 mots)
- [x] Action: Rédiger la version française qui explique le coût du projet (50 mots)
- [x] Action: Rédiger la version anglaise qui explique le coût (50 mots)
- [x] Action: Demander à @sjinko de valider les traductions

**Comment by frroye** [comment]
Salut @iolyd, pour les explications du coût du projet, je me rappelle qu'il y avait eu plusieurs questions à propos de ce qui devait être inclus ou pas dans le coût, l'enjeu de la date à laquelle le projet a été effectué, si c'est une mission complète/un suivi de chantier/plans techniques et autres termes que Rox m'a dit que je n'ai pas 100% compris, etc. Est-ce qu'il y avait une conclusion à propos de ça? Par exemple, as-tu un mail de réponse à cette question aux firmes qui pourrait m'aider à rédiger cette partie?

**Comment by iolyd** [comment]
Salut @frroye, non, nous n'avions pas de réponse définitive comme ça restait un point questionné et débattu par certaines firmes.

L'histoire des dates du projet et des fluctuations de coûts à travers le temps était un point soulevé par certains qui me semblait moins critique et moins pertinent comme les dates clés des projets sont incluses dans les fiches et on estime que les visiteurs de la plateforme pourront faire leur bout de chemin avec ces infos.

Pour ce qui est du calcul de budget, le mot d'ordre pour l'instant est qu'il devrait _prendre en compte tout ce qui est décrit et présenté dans la fiche_. Si le projet comprend des travaux qui sont hors de la portée de la fiche, ça devrait normalement être indiqué clairement à travers la description et/ou dans la liste des travaux. Après,_ c'est certains qu'on mise grandement sur l'honnêteté et la transparence des collaborateurs, et pour la première version ça demanderait trop d'énergie d'encadrer plus strictement cette donnée.

**Comment by frroye** [comment]
@sjinko première version dans content/editeur_fr.md, branche contenu. 

Ici aussi je ne sais pas trop quoi dire, j'ai l'impression que la question sur le type de projets et le type de propriétaire est assez self explanatory? Et je ne suis pas certaine de pourquoi on demande ces informations ou comment elles seront utilisées spécifiquement pour chaque sous section.

**Comment by sjinko** [comment]
Parfait
