### ISSUE TITLE
Task: Implement drizzle custom type and helpers for postgres cube

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#265]
### Task description

At certain places in the app, image metadata are recorded to the database alongside a palette of extracted color. These colors are extracted at upload time and stored as 3d vectors, enabling color-based queries (e.g. proximity-based and containment-based filtering of projects based on their images). The postgres `cube` extension's data type is not part of drizzle-orm, we thus need to provide our own for to/from driver data mapping.

### List of actions

- [ ] Identify key implementation elements in postgres docs (https://www.postgresql.org/docs/current/cube.html)
- [ ] Define desired ts typing strategy (union, discriminated union based on config param, etc.?) in accordance to postgres cube's native behavior and ideal DX.
- [ ] Implement custom type with adequate typing
- [ ] Implement needed cube functions
- [ ] Implement needed cube operators
