### ISSUE TITLE
Task: Rédiger le contenu d'introduction de la section Indicateurs d’exemplarité de l'éditeur de projet

### ISSUE THREAD

**Issue by frroye** [CUPUM/nplex#272]
# Task description
La section _Indicateurs d'exemplarité_ de l'éditeur de projet a besoin de texte pour introduire ses fonctionnalités auprès des utilisateurs.

Max. 300 mots

**Voir content/exemplarite_fr.md et exemplarite_en.md , branche contenu**

# Actions
- [x] Action: Rédiger texte d’introduction de la section indicateur d'exemplarité en français (300 mots)
- [x] Action: Demander à @sjinko de relire le contenu
- [x] Action: Faire les ajustements au texte
- [x] Action: Traduire le texte vers l’anglais
- [x] Demander à @sjinko de valider la traduction

**Comment by sjinko** [comment]
Parfait
