### ISSUE TITLE
Task: Setup tailwind v4

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#277]
### Task description

Tailwind v4 offers many benefits ofver v3 and over our current management of styles through in-house systems heavily based on postcss. We should thus adopt tailwind and _progressively_ deprecate our older system of styles management.

### List of actions

- [x] Install tailwind v4
- [x] Read on setup with sveltekit / vite
- [x] Setup with metaframework appropriately
- [x] Test to make sure things work as expected in dev
- [x] Test in prod
- [x] 🚀 Keep on styling, now using tailwind
