### ISSUE TITLE
Task: Upgrade to svelte 5

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#278]
### Task description

Svelte 5 is now in advanced beta. Most features useful to us are stable and would greatly simplify our work for state management and sharing across components as well as event handling.

We had halted the upgrade to svelte 5 due to `superform`'s unstable support of it, but that is now a thing of the past so we do not have any _legit_ hurdle blocking the update anymore.

### List of actions

- [x] Install svelte 5
- [x] Update required components
- [x] Update required utils
- [x] Test in dev
- [x] Test in prod
