### ISSUE TITLE
Task: Renouveler le nom de domaine

### ISSUE THREAD

**Issue by emmbm** [CUPUM/nplex#282]
### Task description

La location du nom de domaine actuel `nplex.design` arrive à échéance le 25 mai. Son prix est devenu pas mal plus important  qu'au départ et s'élève maintenant à **71.06 $** / année. Il est peut-être temp de considérer un nom alternatif avec une _meilleure_ garantie du prix de renouvellement (dans la mesure du possible).

Par exemple, `nplex.app` est disponible pour ~**21**$ / année**, ou encore `nplex.site` pour ~**18**$ / année, `nplex.xyz` à ~**2.50**$ / année...

### List of actions

- [x] Décider si nous conservons ou non le domaine `nplex.design`
- [ ] ~~Si nécessaire, choisir un nouveau nom de domaine~~
- [x] Transférer le domaine vers le compte GoDaddy de la chaire
- [x] Configurer les DNS host records
- [x] Ajouter et configurer un forfait email
- [x] Payer l'abonnement
- [ ] Action: Check SSL on Outlook
- [ ] Confirm working in production

**Comment by iolyd** [comment]
Salut @sjinko, j'aimerais bien avoir ton avis sur ce issue. J'ai l'impression qu'on s'est fait avoir par un registraire qui gonfle les prix du TLD `.design` depuis le premier renouvellement annuel.

**Comment by sjinko** [comment]
On peut pas déjà transférer le domaine à notre compte Godaddy et conserver celui ci?

**Comment by sjinko** [comment]
A domain lock prevents it from being transferred.
It may be called a "registrar lock", "registration lock", "transfer lock", "domain lock" or "lock".

You need an authorization code (also known as an EPP code or transfer key) from your current registrar.
Some registrars display the authorization code in your account with them, while others email it upon request to the administrative contact's email address for your domain name

**Comment by iolyd** [comment]
Ah, je ne savais pas qu'on avait un compte GoDaddy. En effet, ça pourrait être préférable de tout gérer nos noms de domaines à travers une seule plateforme.

> A domain lock prevents it from being transferred.
> It may be called a "registrar lock", "registration lock", "transfer lock", "domain lock" or "lock".

Comme on possède déjà le nom chez namecheap, on devrait pouvoir faire le transfert sans embûche tant que c'est avant le 25 mai. Par contre, le TLD `.design` appartient en réalité déjà au registre de GoDaddy (on ne fait que l'acheter à travers namecheap) alors je sais pas si ça nous aidera pour le prix.

**Comment by sjinko** [comment]
C'est un prix assez marginal. faisons le transfert

**Comment by iolyd** [comment]
@sjinko Je viens de te partager le code pour compléter le transfert du domaine. Par contre il y aura quelques configurations à faire par la suite au niveau des enregistrements DNS et du forfait pour connecter le tout avec le serveur de l'application.

**Comment by sjinko** [comment]
Le transfert devrait être fait

**Comment by iolyd** [comment]
@sjinko Super, je te reviens asap avec plus de détail sur les autres étapes à compléter et avec un suivi pour ton courriel sur l'avancement du projet.

**Comment by iolyd** [comment]
Salut @sjinko, je m'apprête enfin à déployer une nouvelle version de l'app, mais pour qu'elle fonctionne en production et qu'elle apparaisse au nom de domaine `nplex.design` il reste encore quelques configurations à ajuster dans le compte GoDaddy:

- Ajouter les enregistrements DNS suivants:

| Type | Name | Value |
| :-- | :-- | :-- |
| `A` | `@` | `76.76.21.21` |
| `CNAME` | `www` | `cname.vercel-dns.com.` |

- Payer un [forfait courriel](https://www.godaddy.com/en-ca/email) (nécessaire pour les modules d'authentification des utilisateurs) et le lier au nom de domaine.

**Comment by sjinko** [comment]
Ok, je fais ça sur l'heure du midi

**Comment by sjinko** [comment]
Ok, le forfait courriel a été ouvert. Pour l’enregistrements DNS, j’ai du transférer les nameservers à GoDaddy. C‘est en cours de traitement.

**Comment by sjinko** [comment]
Ok, la seconde ligne du DNS entre en conflit avec une autre configuration du DNS. J’imagine que c'est le CNAME existant?

<img width="860" alt="Screenshot 2024-06-13 at 12 57 51" src="https://github.com/CUPUM/nplex/assets/8132989/b36cce3e-7a0a-4ea1-9a83-697807428bc2">
<img width="867" alt="Screenshot 2024-06-13 at 12 57 58" src="https://github.com/CUPUM/nplex/assets/8132989/135391a1-e972-4568-b72b-7d4751ba85af">

**Comment by iolyd** [comment]
Oui, ça semble être une page par défaut ajoutée par GoDaddy à l'achat du domaine.

Bien reçu pour le courriel. Quand tu auras un moment pourrais-tu m'envoyer par courriel (**pas sur github**) les informations de connection sécurisé (SSL) pour y accéder:
- `username`
- `password`
- `host`
- `port`

**Comment by sjinko** [comment]
Ok, j’ai changé le CNAME www
pour le SSL, je pense qu’il n’est pas installé. GoDaddy a plusieurs forfaits SSL. Il faudrait voir ensemble lequel on prend.

**Comment by sjinko** [comment]
email: info@nplex.design
password: xafmyp-tottid-siGge8

**Comment by sjinko** [comment]
Salut @iolyd, je ne vois pas la nouvelle version en ligne. Peux-tu me dire ce qu’il en est?

**Comment by iolyd** [comment]
Salut @sjinko, il y a quelques éléments que je n'ai pas pu compléter la semaine dernière et sur lesquels je dois travailler encore. Elle sera déployée dans les prochains jours, cette semaine. Je vais faire un tour des issue aussi pour indiquer quelles tâches sont complètes au stade _développement_ mais en attente sur d'autres pour le déploiement, et donc encore ouvertes au stade _production_.

**Comment by iolyd** [comment]
Salut @sjinko,

Il y a un ajustement à faire au niveau de la configuration DNS:

```
Remove the following conflicting DNS record from your DNS provider:

Type     Name     Value
A        @        3.33.130.190
A        @        15.197.148.33

Afterwards, set the following record on your DNS provider to continue:

Type     Name     Value
A        @        76.76.21.21
```

**Comment by sjinko** [comment]
Tu as les informations de log in dans le issue

**Comment by sjinko** [comment]
Ok, je rends compte que c'est pas wise pcq c'est un repo public. Je te les envoie par message

**Comment by sjinko** [comment]
En fait, je viens de checker le DNS, et c'est déjà ces infos qui y sont
