### ISSUE TITLE
Task: Compléter et soumettre la reddition de compte de clôture pour le programme Partenariat UdeM

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#283]
### Task description

> Je me permets de vous contacter dans le cadre de la réédition de compte annuelle 2023-24 du financement de votre projet Partenariat-UdeM : Nplex: Plateforme web de valorisation des petits projets locaux exemplaires en design d’aménagement, pour lequel un financement de 50 000$ a été octroyé. Votre partenaire pour ce projet est le Bureau du design de la Ville de Montréal.
>  
> Le projet a pris fin en date du 30 avril 2024, il s’agira donc d’un rapport de clôture.
>  
> Vous trouverez en attaché :
> - un gabarit de lettre des contributions du partenaire : à faire parvenir à votre/vos partenaires, pour qu’il collige les dépenses en espèces et/ou en nature qui ont été faites durant l'année financière (soit du 1er mai 2023 au 30 avril 2024, et y appliquer sa signature.
>  
> - un gabarit excel dans lequel vous pourrez colliger les informations du/des partenaires, et détailler les dépenses réalisées sur la contribution Partenariat-UdeM pour l’année 2023-24.
>  
>  **Dans les deux cas, les champs à remplir sont surlignés en jaune.**
>  
>  
> Merci de me retourner les documents complétés dans un seul et même courriel, d’ici le VENDREDI 21 JUIN 2024 au plus tard.

Les gabarits partagés sont un peu confus nécessitent d'être ajustés puis validés avec N. Delaunay.

### List of actions

- [x] Se familiariser avec les documents
- [x] Récupérer sommaire des dépenses auprès de `recherche-depenses@ame.umontreal.ca`
- [x] Mettre de l'ordre dans les documents (gabarits confus...)
- [ ] Valider les informations avec N. Delaunay
- [x] Envoyer un courriel aux partenaires concernés pour obtenir attestation
- [x] Compléter le dossier
- [x] Soumettre le dossier

**Comment by iolyd** [comment]
Salut @sjinko, j'aurais besoin de tes conseils pour savoir comment approcher les ajustements demandés par J. De Guire au niveau des montants spécifiés dans l'attestation de contribution du Bureau du design. Les dates de paiement qu'elle indique précèdent effectivement la période à couvrir dans cette reddition de compte et sont celles prévues dans l'entente avec la Ville. **Cependant si je m'en tiens à ses courriels, les versements ont été envoyés plus tard, le 18 avril et le 2 mai**.

Je comprend qu'il y a un enjeu politique derrière sa demande, mais je ne suis pas certain que ce soit compatible avec nos propres enjeux pour cette reddition de compte. D'ailleurs, en relisant nos échanges passés avec J. De Guire, j'interprète que même le dernier versement respecte l'entente de la ville: nous avons déposé le rapport final dans les 30 jours suivant la terminaison du projet.
