### ISSUE TITLE
Epic: Structuration des données de fiche acteur

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#29]
# Epic description

Ce epic sert à développer et présenter de manière exhaustive et concise la structure des données pour les fiches _acteur_.
La mise en place _intelligente_ des fiches d'acteurs demandent une intégration réfléchie avec le système d'utilisateurs: une fiche d'acteur peut être «incarnée» par un utilisateur ou non. À ce titre, nous devons déterminer le UX flow de l'utilisateur et des admins pour régir ces «incarnations» potentielles.

Il est proposé de fonctionner d'une manière similaire au processus d'obtention de rôle, avec une démarche de soumission simplifiée par l'utilisateur puis de validation par l'administrateur.

# Tables de données et listes (énumérées et contrôlées)

To do...

# To do

- [ ] Établir le dictionnaire des données propres aux fiches-acteurs
- [ ] Définir les modes de gestion des profils d'acteurs
  - [ ] liés à utilisateur authentifié
  - [ ] non-liés à utilisateur authentifié

**Comment by iolyd** [comment]
Out of scope
