### ISSUE TITLE
Epic: Restructure repo to deploy dockerized front-end and back-end

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#40]
# Restructure repo to deploy dockerized front-end and back-end

## Epic Description

For guidance, look into: https://www.digitalocean.com/community/tutorials/how-to-secure-a-containerized-node-js-application-with-nginx-let-s-encrypt-and-docker-compose

## List of Tasks (Complete in order)

- [x] Dockerize front-end (sveltekit) app
- [ ] Customize Supabase docker image
- [x] Restructure repo directories
- [x] Test deployment

**Comment by iolyd** [comment]
This issue is out of date with the newly targeted deployment pipelines.
