### ISSUE TITLE
Task: Evaluer le rendu du CENR pour la phase 1

### ISSUE THREAD

**Issue by sjinko** [CUPUM/nplex#49]
# Task: Evaluer le rendu du CENR pour la phase 1

## Task Description
Valider le contenu du document rendu par le CENR pour la phase 1 (envoyé par S.E. le 2021.12.22): https://cirrus.gnp.umontreal.ca/index.php/s/xazfQd5oDBsQSMo

## Epic Parent

[Parent: Gestion financier de Nplex](https://github.com/CUPUM/general/issues/44)

## List of actions
1. [x] Lire et commenter le document
2. [x] Tester la mise en place de l'architecture proposée dans Supabase
   - [x] S'il y a lieu, noter les problèmes logiques
3. [x] Attendre la version finale (validée par Christian)
   - [x] Réviser intégration d'essaie dans Supabase à partir des modèles logiques
3. [ ] Présenter l'évaluation

**Comment by iolyd** [comment]
Je ferme ce issue en préférence de #55
