### ISSUE TITLE
Task: Rencontre Suivi des projets VdeM du 26 janvier

### ISSUE THREAD

**Issue by sjinko** [CUPUM/nplex#51]
# Task Description

Notes de la rencontre de suivi du 26 janvier.

# List of actions
- [x] Action: Participer à la rencontre
- [x] Action: Transcrire les éléments importants dans le issue
- [ ] Suivi avec SC (VdeM) sur réception du premier paiement (informer EBM lors de la réception ou faire le suivi)
- [x] Ajouter lien github du projet au document de reddition de compte
- [ ] #53

**Comment by sjinko** [comment]
Salut @iolyd, je ne pourrai pas être présent à la rencontre de cet après-midi. Peux-tu t’en charger?

**Comment by sjinko** [comment]
Salut @iolyd, tu as pris des notes durant ton tete a tete avec Sylvie, n’hésite pas à les inscrire ici pour archivage.

**Comment by iolyd** [comment]
La rencontre était plutôt une présentation de notre état du travail et les retours étaient brefs. Je n'ai pas vraiment eu d'éléments à pendre en note outre ce qui se trouve dans la liste des actions ci-haut et le contenu du issue qui y est déclaré. J'ai apaporté quelques modifications aux endroits indiqués (wiki du projet et reddition de compte) au moment même de la rencontre.
