### ISSUE TITLE
Task: Suivi VdeM février

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#57]
# Task Description
Notes de la rencontre de suivi du 22 février.

# Notes / tasks
- [x] Compléter documentation de l'équipe (partenaires et comités)
- [x] Consulter la boussole qualité
- Protocole de communication de la ville (présentation graphique de la ville en tant que partenaire)
  - Au moment venu, envoyer les demandes d'approbation à Sylvie avant de soumettre à Eric (responsable des comm)
- [x] Vérifier date de prochaine reddition de compte
  - Livrables prévus dans le projet
  - [x] Évaluer avancement
  - [ ] Rédiger reddition de compte

**Comment by iolyd** [comment]
Selon la convention acceptée entre la Ville et la CUPUM, la prochaine reddition de compte est prévue à la livraison d'une première version fonctionnelle de l'application, soit en septembre (mais flexible d'après Sylvie).

La rédaction est donc reportée à ce moment.
