### ISSUE TITLE
Epic: Produire le template pour les fiches de projet

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#61]
### Epic Description

Ce epic sert de lieu pour définir et documenter progressivement la structure des fiches-projet en termes de **tables,** de **listes**, et de **métadonnées**. Les colonnes des tables de la base de données correspondent aux métadonnées prévues pour constituer les entités,  où une métadonnée peut faire référence à une liste (table simple qui contient des options, paramètres, ou qui agit à titre _d'enum_). Ces listes peuvent être _énumérées_ (statiques et gérées uniquement par les administrateurs directement dans la base de données) ou _contrôlées_ (modifiables par les éditeurs à travers l'interface web). Les indications nécessaires sont incluses pour spécifier quels éléments sont exigés ou optionnels au moment de la création de nouvelles entités, à la saisie de données.

Nous y présentons _mécaniquement_ et de manière exhaustive une version ajustée des propositions livrées par le CEN-R. Pour un survol explicatif sous forme de texte, référez-vous au document évaluant le livrable du CEN-R.

(À faire: ajouter un lien vers le document ici).

#### Références

La version ajustée que nous présentons ici s'appuie aussi sur un ensemble de références et d'exemples:

- Fiche bâtiment du processus de demande de permis
- Grille des usages et des normes du règlement de zonage (arrondissement d'Outremont) / Fiches de zonage
- Métadonnées mise en évidence sur les plateformes identifiées lors de la veille: https://github.com/CUPUM/nplex/issues/11
- [Comptes-rendus d'atelier](https://github.com/CUPUM/nplex/wiki/Comptes-rendus)

### Tables de données et listes (énumérées et contrôlées)

- Les champs exigés sont marqués avec « * ».
- Les colonnes de métadonnées relationnelles faisant référence à d'autres tables ou listes doivent préciser la colonne « étrangère » (_foreign object keys_) utilisée pour référence.
- Les tables relationnelles doivent avoir un nom comportant en préfixe le nom de la table mère qui leur est contextuelle et pour laquelle une métadonnée est utilisée comme colonne primaire dans la table relationnelle. Par exemple, la table des événements de projet portera le nom `projects_events`.
- Les rangées des tables de listes sont ici remplies dans la mesure du possible pour aider à illustrer la structure et la signification des données.

#### Document de travail

La version de travail excel (pré-traduction vers markdown) est [accessible ici](https://udemontreal-my.sharepoint.com/:x:/g/personal/emmanuel_beaudry_marchand_umontreal_ca/Edx0MFsSN7tIhd5X66cGnmYBqZGBp1_rAY9HR27G5Q00LQ?e=N2Ddpi).

### List of Tasks

- [x] Compléter une première version d'ensemble
- [x] Ajuster selon retours de l'atelier 2 (#47)
- [x] Task: Concevoir l'interface graphique de la fiche projet
- [ ] Task: Développer l'interface graphique de la fiche projet

**Comment by AgathePC** [comment]
@iolyd Je ne trouves pas la version de la fiche projet que tu m'as montrée hier sur Figma. La version dans Design-system n'est pas la même.
