### ISSUE TITLE
Task: Rencontre avec équipe du CMAQ sur enjeux de données

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#63]
# Task Description

Lors du suivi de fin de mois de mars auprès de la Ville, il est apparu qu'il serait pertinent d'échanger avec l'équipe du CMAQ travaillant sur la plateforme des intérieurs patrimoniaux pour partager nos réflexions sur la structuration de nos données et sur la conception des _flows_ de saisie. Leur équipe navigue actuellement des défis et enjeux similaires à ceux que nous rencontrons dans notre projet au niveua de la confidentialité de certaines données et de la simplification / l'optimisation des formulaires.

À cet effet, Catherine Charron nous propose une rencontre pour poursuivre la discussion entammée pendant la séance de suivi des projets soutenus par la Ville.

## Points de discussion pertinents

- Enjeux de confidentialité
  - Données/métadonnées concernées
  - Défis et questionnements pour la saisie:
    - Saisir des données précises et limiter leur diffusion? ou
    - Saisir des données imprécises?
  - Solutions envisagées
    - Comment permettre aux utilisateurs de déterminer le niveau de précision qu'ils acceptent de partager?
- Structure des données
- ...

# List of actions
- [x] Explorer le document de travail partagé par Catherine
- [x] Répondre à Catherine pour organiser une rencontre
- [ ] Partager un document de travail simplifié (par la même occasion, préparer le contenu pour l'atelier)

**Comment by sjinko** [comment]
Salut, oui. vendredi 14-15h dans les deux cas.

**Comment by iolyd** [comment]
Les points pertinents tirés de la rencontre seront intégrés directement dans les issues concernés.

Voir:
- #11 
- #61
