### ISSUE TITLE
Epic: Concevoir un modèle d'affaires ou de pérennisation financière

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#64]
# Epic Description

Il serait pertinent de concevoir un modèle d'affaire et d'y établir une vision à moyen-long termes pour la plateforme et sa gestion. Cette ressources permettrait d'identifier plus facilement les potentialités de financement et de partenariat. Pour ce faire, il est proposé de chercher des ressources internes à l'université qui pourraient nous aider à définir un plan d'affaire viable tout en étant cohérent avec les visées initiales du projet et les contraintes des financement déjà embrayés.

### Question à se poser

- Comment assurer la pérennité de l'application?
- Qui est propriétaire de la plateforme livrée?
  - Selon l'entente actuelle avec la ville: La chaire UNESCO (et non la ville)
  - Appartient-elle aussi à l'Université?
- Pérennisation de mise en fonction
  - Quelles sont les conditions d'utilisations détaillées de CalculCanada
    - Le projet peut-il y être hébergé au-delà de sa période de développement, après le «dépôt»?
    - Est-ce que d'autres solutions d'hébergement sont disponibles à l'interne de l'UdeM?
- Qui seraient les partenaires potentiels?
  - Y aurait-il d'autres villes ou d'autres structures au Québec et au Canada qui pourraient y voir un intérêt?
  - Faire un brainstorming sur qui pourrait être intéressé par le projet, par l'application à livrer. (schématiser en cercles de proximité selon le niveau d'intérêt potentiel)
    - Réfléchir à des fondations
      - [Fondation Béati](https://www.fondationbeati.org/)
      - _Autres partenaires du domaine de la construction_?
    - Autre avenue: formation d'un OBNL?
      - Axelys (remplaçant d'Univalor): Service de valorisation en société et culture
      - Centre d'entreprenariat
  - Retravailler la demande de financement Partenariats-UdeM pour soumettre avant juin
    - Démontrer **clairement** comment le projet répond à l'objectif requis d'implanter l'innovation chez les partenaires
    - Faire valoir davantage la perspective des partenaires dans les lettres (2 à 3 devraient suffire)
    - Consulter la _Matrice du modèle d'affaires responsable_ partagée par GL (produite à l'ULaval)

# List of Tasks

- [x] #67
- [x] #72
- [ ] Attendre suivis de GL
  - [ ] Solutions d'hébergement
  - [ ] Suivi à propos d'Axelys
  - [ ] Mise en lien avec le centre d’entreprenariat de l’UdeM
- [x] #66

**Comment by iolyd** [comment]
Closing as outdated.
