### ISSUE TITLE
Task: Définir les postes d'engagement

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#65]
# Task Description

Définir les postes d'engagement requis et leurs «scope» de tâches/responsabilités respectifs.

# List of actions

- [ ] Mettre de l'ordre dans les issues
- [ ] Définir les issues manquants
- [ ] Assigner des postes de travail aux issues («_Main duty_»)
- [ ] Produire des évaluation de charge de travail
- [ ] Rédiger des affichages spécifiant les compétences recherchées

**Comment by iolyd** [comment]
Salut @sjinko, je vais ici élaborer progressivement les postes d'auxiliaires envisageables discutés hier. Nous pourrons en rediscuter prochainement.

**Comment by sjinko** [comment]
Salut Emmanuel. Peux-tu me dire où tu en es dans cette réflexion? Aussi, je pourrais engager une personne avec un profil plus urbanisme pour t’aider avec les aspects liés aux partenaires. Qu’en dis-tu?

**Comment by iolyd** [comment]
Salut @sjinko, je vais ajuster sommairement la descriptions des postes en fonction de ce qui est ressorti de notre rencontre avec GL. Mais de manière générale, je crois que si nous engageons une personne avec un profil urbanisme elle pourrait bien remplir le rôle du premier poste décrit ci-haut.

En ce qui concerne le poste de développeur, j'attendrais pour l'évaluation du CEN-R pour voir quelles tâches ils pourraient assumer de manière fiable.

**Comment by iolyd** [comment]
En complément à la description du premier poste, [voici la fiche pour l'affichage](https://udemontreal-my.sharepoint.com/:b:/g/personal/emmanuel_beaudry_marchand_umontreal_ca/EejOZ57okwRBs5vxEeg8MhIBkN7QESiLfIJc7LgzNhVC3A?e=7hbZOP).

**Comment by sjinko** [comment]
Salut, je n‘arrive pas à éditer le document, mais il faudrait mettre les heures totales, par exemple :
* 340 heures entre 11 mai et le 31 août (equiv. 20 heures par semaine)

**Comment by iolyd** [comment]
Le total d'heures est indiqué en haut. Il faudrait les préciser aussi dans les _conditions d'exercices_?

![image](https://user-images.githubusercontent.com/52970928/166264026-bd692767-4bbc-4dc4-8d53-2e59de288d94.png)

**Comment by sjinko** [comment]
je préfère qu’on les précise aussi. Merci de mettre plutot 300 heures pour l’instant et on réajuste si nécessaire.
________________________________

**Comment by iolyd** [comment]
@sjinko Est-ce que je peux lancer la démarche pour afficher le poste profil urbanisme (le premier poste décrit dans le corps du issue)? Avais-tu déjà une personne en tête?

**Comment by sjinko** [comment]
Tu peux lancer la démarche. J’ai quelque qu’un en tête mais il fait un affichage de toute façon.

Peux tu envoyer à Tony Lambert en me mettant en cc
________________________________
