### ISSUE TITLE
Task: Préparer une nouvelle version de la demande au programme Partenariat-UdeM

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#66]
# Task Description

[Une nouvelle mouture du programme Partenariats-UdeM est présentement en cours](https://recherche.umontreal.ca/services-aux-chercheurs/subventions-secteur-sante/partenariat-udem/). Notamment, il est maintenant possible d'inclure de nouveaux types de partenaires, dont des villes (et des arrondissements?):
> _Les organismes publics et parapublics, tels des municipalités, des centres de services scolaires, des hôpitaux, des sociétés de transport, peuvent aussi être inclus comme partenaires dans le montage des projets._

Geneviève nous confirme que la contribution de la Ville de Montréal pour l'instant non-déboursée est admissible. Il faudrait donc monter la demande autour du patenariat avec la Ville de Montréal et recuillir des lettres auprès de divers acteurs (membres du comité de conseil, Bureau du design, etc.) pour bien faire valoir l'implantation escomptée du livrable.

À titre d'information, la contribution _à venir_ de la Ville est ainsi décrite dans l'entente:

> 5.2.2 Pour l’année 2022 :
> - 5.2.2.1 une somme maximale de trente mille dollars (30 000 $) à la
présentation de la première version opérationnelle, à la
satisfaction du Responsable;
> - 5.2.2.2 une somme maximale de sept mille cinq cents dollars (7 500 $)
suivant le lancement de la plateforme et la reddition de compte;

## Documents de travail

Le répertoire de travail sur OneDrive est [accessible ici](https://udemontreal-my.sharepoint.com/:f:/g/personal/emmanuel_beaudry_marchand_umontreal_ca/Ev7Ji6hUsLVLr9zhKKxj_pkBLXQq0SwOttGCz3UaA9-KdA?e=5K2awk). Celui-ci comprend pour l'instant une copie de la version précédente de la demande, à utiliser comme base pour le montage de la nouvelle version.

## Commentaires de la version précédente

Les commentaires d'évaluation du jury nous aideront à monter la présente demande de manière à mieux répondre à leurs attentes.

> Le projet présenté s’inscrit dans une suite du projet subventionné via le Programme de soutien aux projets technosociaux innovants d’Inven_T. La proposition s’attaque à un enjeu important et clairement exprimé. De plus, soulignons que la proposition répond à un commentaire soulevé à la première évaluation qui recommandait l’intégration de partenaires autres que la Ville de Montréal. Plusieurs partenaires sont inclus et les partenaires sont nombreux et pertinents. Toutefois, au regard des objectifs du programme visant l’implantation et la diffusion d’innovations au sein des entreprises québécoises, la demande n’a pas réussi à mettre en évidence comment les résultats seront investis au sein des entreprises impliquées dans le projet. Il aurait été pertinent que les partenaires précisent dans leur lettre quel sera l’impact du projet pour leur entreprise et comment la solution sera diffusée ou utile.
>
> La proposition est innovante et a un potentiel de retombées positives. Pour ces raisons, nous vous encourageons fortement à soumettre de nouveau dans le cadre du concours Partenariat-UdeM ouvert à la communauté UdeM. De plus, l’ajout de nouvelles catégories de partenaires admissibles, dans cette nouvelle mouture du programme, permettrait de mettre en évidence la contribution de la Ville de Montréal, notamment.

## Commentaires version 2 dépôt pour révision

Après dépôt d'une version de la demande pour révision, GL nous propose d'apporter quelques modifications. Les voici avec des réponses suggérées:

> - Arrimage avec les priorités stratégiques institutionnelles : ajouter quelques lignes pour évoquer comment le projet s’arrime avec les priorités stratégiques institutionnelles. Vous n’avez qu’à identifier au minimum une priorité et expliquer brièvement en quoi le projet vient répondre à cette priorité. Pour ce faire, voir le plan d’action en recherche 2022-2027 : https://recherche.umontreal.ca/fileadmin/recherche/documents/user_upload_ancien/La_recherche_a_UdeM/Fichiers/FIN-Plan_ACTION-VRRDCI-FR_2022_2027.pdf ou la plan stratégique institutionnel : https://www.umontreal.ca/public/www/images/planification-stategique/Documents/Plan_strategique_UdeM_2032.pdf

- Ancrages possibles:
  - _Création, culture et imaginaires_: valorisation du patrimoine bâti, intégration de perspectives variées dans la conception du projet
  - _Rapport sociaux, démocratie et responsabilité_: aménagement et transformation des espaces
- Plan d'action VRRDCI et priorités:
  - Soutenir la collaboration
    - Valoriser les savoirs, savoir-faire et savoir-être issus de l'epérience et de la pratique (inclusion de divers points de vue des milieux utilisateurs escomptés)
  - Maximiser l'impact
    - Développement d'un leadership en matière de valorisation d'une culture du design informée, partagée, et innovante en aménagement à Montréal
- Plan stratégique 2022-2032:
  - Développement d'un outil numérique qui vise ultimement l'accompagnement de la société dans une perspective de bien commun en favorisant la communication et l'adoption de bonnes pratiques en aménagement

> - Pour renforcer la pertinence et l’engagement des partenaires dans le projet, il aurait été pertinent d’avoir une lettre d’au moins une des firmes d’architectures qui participeront au projet et qui témoignent de leur intérêt, leur engagement et ce qu’ils en retireront. Si jamais c’était possible ce serait un gros plus, mais sinon, le projet est tout à fait déposable dans sa forme actuelle.

- L'engagement des firme n'est pas comptabilisé dans notre demande, j'ai plus de difficulté à percevoir l'utilité d'intégrer une ou des lettres de leur part.

> - Au niveau du calendrier, les étapes sont bien détaillées. Toutefois, on voit mal où commencent les étapes faisant l’objet de la présente demande. Ce serait aussi l’occasion d’insister sur le besoin d’obtenir le financement pour réaliser les étapes subséquentes. Cet élément faciliterait la compréhension du projet et comment il s’insère dans cette demande Partenariat-UdeM.

- Paragraphe ajouté pour couvrir ce point:
  > ...De février à mai 2022, l’équipe de développement a initialisé les systèmes serveur essentiels au déploiement web du projet, configuré les fonctionnalités de manipulation de la base de données, puis a mis en ligne une version de travail comportant les éléments de base de l’interface utilisateur.
  > 
  > **Jusqu’ici, le financement requis pour soutenir l’avancement des tâches a été couvert par la première phase du partenariat avec le Bureau du design de la Ville de Montréal, le programme de soutien aux projets technosociaux innovants Inven_T de l’Université de Montréal, et la chaire UNESCO elle-même. À compter de l’été 2022, la poursuite des chantiers de longue durée et le démarrage de nouvelles tâches s’inscrivent principalement sous le second bloc de financement de la ville ainsi que le financement escompté en lien avec la présente demande.**
  > 
  > De juin à août, le développement de la plateforme se poursuit avec la connexion de l’application web aux divers services de données utilisés pour alimenter le contenu des fiches et les fonctionnalités de recherche...

# List of actions

- [x] Étudier les nouvelles modalités du programme
- [x] Vérifier quelles contributions peuvent être comptabilisées
  - Qu'en est-il des contributions déjà embrayées par la VdeM ?: Elle est valide pour comptabilisation dans la demande.
- [ ] Identifier les nouvelles occasions de partenariat
- [x] Ajuster la demande précédente en fonction des commentaires reçus de la part du jury
- [x] Réviser le budget et sa justification en fonction du montant atteignable (37500 * 2)
- [x] Recueillir lettre(s) d'intention auprès de:
  - [x] Ville de Montréal (Sylvie ou Patrick?)
- [x] Soumettre pour relecture
- [x] Compléter les modifications pour répondre aux commentaires de GL
- [x] Faire approuver par SK
- [x] Compléter dépôt final

**Comment by AgathePC** [comment]
Bonjour @iolyd. Je te tiens au courant parce que je vais être à mon bureau à l'INRS cet après-midi pour récupérer mon chargeur de laptop (à moins que je l'ai oubliée à la faculté). Si je le retrouve, je serai en mesure de faire une rencontre teams. Sinon, selon l'heure qu'il est, je pourrai passer à la faculté. Dans tous les cas, je pensais venir toute la journée demain si quelqu'un est là avec les clés. Bref, je te tiens au courant.

**Comment by iolyd** [comment]
@AgathePC C'est bon pour demain, je serai à l'école. Autrement, je crois que ton chargeur d'ordinateur portable se trouve effectivement ici, à la chaire.

**Comment by AgathePC** [comment]
@iolyd dans ce cas je passerais le chercher maintenant, si tu es toujours là?

**Comment by iolyd** [comment]
@AgathePC oui je suis à l'école pour le reste de la journée. Je m'absenterai probablement un peu entre 1h30 et 2h30 pour dîner, mais autrement je serai au local 4112.

**Comment by AgathePC** [comment]
@iolyd J'ai fait quelques modifications, en bleu. Comme tu avais dit, je ne pense pas qu'il est nécessaire de changer plus, selon les commentaires reçus. Par contre, j'aimerais m'assurer que c'est vraiment bénéfique d'enlever les premiers partenaires complètement du texte, puisque les commentaires allaient plus dans le sens d'ajouter la Ville de Montréal, selon ce que j'en comprend : _L’ajout de nouvelles catégories de partenaires admissibles, dans cette nouvelle mouture du programme, permettrait de mettre en évidence la contribution de la Ville de Montréal, notamment._ Bref, n'hésite pas à me faire des commentaires pour que je puisse m'ajuster au besoin.

**Comment by iolyd** [comment]
@myriamgui, voir ce issue pour réf sur la préparation de la nouvelle demande.

**Comment by sjinko** [comment]
Salut, oui, je pense que tu peux simplement écrire à Sylvie pour lui demander la lettre. Il faudrait qu’on puisse déposer la demande avant que la ville nous envoie son second versement, autrement, on ne pourra pas inclure ce montant.
________________________________

**Comment by iolyd** [comment]
Salut @sjinko, le prochain versement de la ville est prévu vers septembre, et plus spécifiquement suite au dépôt d'une première version fonctionnelle de l'application. J'anticipe soumettre le dossier de demande cette semaine ou la semaine prochaine au plus tard selon les retours de Sylvie et de Geneviève, donc ça devrait être bon sur ce point.

Avec les commentaires de Myriam et le travail d'Agathe, nous avons complété la révision du descriptif du projet pour y donner un peu plus de place au partenariat avec la Ville, il ne me reste donc qu'à établir les coûts rattachés aux différents postes de dépense dans la justification du budget. J'anticipe que la rencontre qui aura lieu prochainement avec le CEN-R pour regarder leur offre de service m'aidera à évaluer ces coûts.
Le seul point qui me tracasse un peu pour l'instant est de s'assurer que la ville fasse bien valoir sa participation dans la/les lettres d'appui, car cette participation n'est pas si évidente pour l'instant (elle prend surtout place à travers le temps approuvé pour les membres du comité de conseil).

Voici le message que je pensais envoyer à Sylvie, mais dont j'ai l'impression ne met pas assez d'emphase sur le besoin de faire valoir la collaboration de la Ville:

>Bonjour Sylvie,
>
>En réponse à une opportunité de financement qui nous est présentée par l’Université de Montréal (https://recherche.umontreal.ca/services-aux-chercheurs/subventions-secteur-sante/partenariat-udem/) pour encourager les projets de recherche menés avec l’appui de partenaires privés, publics, et/ou parapublics, nous sommes présentement en montage d’un dossier de demande qui s'inscrit dans le projet _Nplex_. Le financement accessible à travers ce programme est établi selon la contribution totale (en espèce et en nature) des partenaires du projet, et nous avons reçu confirmation de l’école que la portion non-engagée de la contribution de la Ville est admissible. Le programme tient pour objectif principal de supporter l’implantation et la diffusion d’innovations au sein des milieux de pratique des partenaires québécois, le dossier doit donc faire valoir la collaboration et les retombées escomptées auprès du partenaire à l’aide de lettres d’appui. Comme le jury semble percevoir plus difficilement les retombées que nous avions identifiées avec les bureaux d’architecture qui ont acceptés de nous accorder bénévolement du temps et des données pour tester l’alimentation de la plateforme cet automne, et que les partenaires publics sont désormais admissibles, nous avons choisi d’étayer notre demande autour du support obtenu de la Ville de Montréal.
>
>Le financement supplémentaire serait alloué à l’organisation et l’animation d’activités participatives impliquant des élus et experts membres de CCU ainsi que des tables de quartier. Une portion des fonds servirait aussi au développement de divers éléments plus techniques au niveau de l’infrastructure applicative et serveur, éléments pour lesquels nous prévoyons faire appel aux services d’une expertise externe. Afin de compléter le dossier, nous devons y joindre une ou plusieurs lettres d’appui du partenaire comptabilisé dans nos calculs budgétaires. À cet effet, nous nous demandions si une personne du Bureau du design et/ou de la Ville de Montréal serait en mesure de rédiger une lettre couvrant les points suivants prescrits par l’université :
>
>- Confirmation de la participation au projet et description de l’engagement;
>- Pertinence du projet pour la Ville et le Bureau du Design;
>- Description de la collaboration;
>- Contribution : confirmer le type de contribution (en espèce) et le montant. Ici, seule la portion non engagée du financement de la Ville est à prendre en compte, soit 30 000$ + 7 500$, pour un total de 37 500$.

Crois-tu que c'est suffisant?

**Comment by iolyd** [comment]
Salut @sjinko et @myriamgui, la description du projet et la justification du buget sont prêtes pour relecture. Je soumetterai ensuite à Geneviève pour une lecture finale avant le dépôt. Entretemps, j'attends un retour de Sylvie qui nous fournira la lettre d'appui du Bureau du design de la ville pour le montant indiqué dans la demande.

**Comment by myriamgui** [comment]
Salut @iolyd, pour ma part je n'ai pas d'autres commentaires, la demande me semble très bien

**Comment by sjinko** [comment]
Salut @iolyd, le buget m’a l’air très bien. 

Concernant la demande, j’ai une suggestion: il faudrait adapter les deux premiers paragraphes à ce que le Bureau du Design mettra de l‘avant dans sa lettre. Afin que leur « intérêt » paraisse central au projet, il faut vraiment nous y aligner. 

Dans la section « justification du budget », ne pas oublier de remplacer le « N » par le montant.

Sinon, je vois qu’il y a plusieurs commentaires qui se résument à une seule lettre. Peux-tu me dire de quoi il s’agit?

**Comment by iolyd** [comment]
Salut, @sjinko, bien reçu, je vais apporter les ajustements nécessaires. Les lettres en commentaires me servent simplement de référence pour les items budgétaires définis dans le tableau du document excel.

**Comment by iolyd** [comment]
Salut @sjinko, j'ai mis à jour le message principal de ce issue pour réfléter le retour de GL.

Le document de travail sur OneDrive comporte aussi maintenant les modifications proposées (repérables via les commentaires). Je te laisse valider avant que je compose et dépose la version finale de la demande en format PDF.

**Comment by sjinko** [comment]
Salut @iolyd, ca me parrait bien. Tu peux soumettre.


________________________________

**Comment by iolyd** [comment]
Je ferme ce issue car la demande a été reçue avec confirmation que le dossier était complet.
