### ISSUE TITLE
Task: Atelier de présentation et test(s) d'usage avec équipe de la chaire

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#69]
# Task Description

Cet exercice servira à tester la formule d'atelier utilisée avec les collaborateurs externes, et à identifier des premières lacunes  fonctionnalités spécifiques manquantes ou problématiques. 

## Déroulement prévu

- Présentation sommaire de la plateforme telle que développée **30 minutes** (20 min de présentation, 10 min pour questions)
  - Structure
  - Fonctionnalités principales
- Survol en groupe du guide d'exemplarité et commentaires **30 minutes** (20 minutes de présentation, 10 minutes de questions et de discussion)
  - Est-ce que les exigences du guide d'exemplarité sont réalistes à votre avis?
  - Y-a-t 'il des critères importants qui ont été oubliés?
- Exploration en groupe avec discussion et recueil des avis pour chaque page et fonction **45 minutes**
  - Déterminer des questions à poser pour démarrer la discussion 

## Participants
| Participant | Affiliation | Rôle |
|--- | --- | --- |
| Emmanuel Beaudry Marchand | CUPUM | Animateur |
| Shin Koseki | CUPUM | Participant |
| Participant 2 | CUPUM | Participant |
| Participant 3 | CUPUM | Participant |
| Participant 4 | CUPUM | Participant |

## Matériel

- Salle LIP ou autre salle de rencontre
  -  Écran central
- Ordinateurs portables ou tablettes grand format pour permettre aux participants d'interagir avec l'application
- Application pour enregistrement de l'écran et du microphone afin d'étudier UX et réactions

# List of actions

- [ ] Présentation [Figma](https://www.figma.com/file/CTOK91eEnegwRmM68ygj5m/Presentations?node-id=618%3A1421)
- [ ] Réviser maquettes graphiques
- [ ] Relire / compléter compte-rendu atelier 2
- [ ] Préparer présentation
  - [ ] Structure des services
  - [ ] Ateliers passés
  - [x] Structure du site (sitemap)
  - [x] Maquettes graphiques / web
