### ISSUE TITLE
Task: Workshop pour discuter des opportunités de financement et de partenariat

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#72]
# Task description

Afin de nous aider à monter le modèle d'affaires nécessaire pour pérenniser la plateforme sur le plan financier, il serait pertinent d'identifier les opportunités de financement qui seraient pertinentes et compatibles avec le format du projet, les partenaires actuels, et le livrable prévu.

Quelques questions et contraintes à prendre en compte:

- La plateforme ne devrait pas avoir un caractère commercial;
- Les fonctionnalités seront potentiellement spécifiques au cadre de la VdeM, étendre la portée du projet risque d'impliquer plus de travail et d'ajustements;
- ...

Nous proposons d'organiser un court atelier _brainstorm_ pour aborder le sujets.

# To do

- [ ] Inviter équipe à l'atelier
- [ ] Définir le moment
- [ ] Synthétiser les résultats de l'atelier
