### ISSUE TITLE
Task: Revise route guarding implementation

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#76]
# Task Description

The route guarding strategy and the guard check function work properly, but orbiting everything around the root layout's load function and the `$route`store can lead to complications when adding new routes or revising the app's routing architecture. It would be easier to manage guards on a per-layout basis.

This introduces a new concern though: How should we manage updating the session's `prevnav` upon navigation. Taking care of this at every layout's level is overly cumbersome. A simple handler passing the prop could be kept in the root layout (as is currently implemented), or we could alternatively work using a different strategy that doesn't rely on updating the`session` store. The challenge with the latter is to ensure access to `prevnav`'s value form within the load function for client-specific server redirects.

# List of actions

- [x] Remove link between `$route` store and route guarding on the root layout;
- [x] Strip `guards` from items in global `routes` array;
- [x] Add per-layout route guarding inside load functions

**Comment by iolyd** [comment]
Base implemented with 3601dac9e2e4e2fd98567782389f00ab5444dae5
