### ISSUE TITLE
Task: Rencontre hebdomadaire de la chaire (18 mai)

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#78]
# Task Description

La rencontre hebdomadaire de la chaire aura lieu ce mercredi au local AME 3072, de 11h00 à 12h00.
Elle regroupera toute l'équipe présente à Montréal, incluant les auxiliaires des divers projets (nplex, aggrégateur, etc.) et servira à faire un bref suivi des tâches et prochaines étapes.

## Notes de rencontre

- [x] @iolyd Établir timeline pour montage de nouvelle demande au programme Partenariat-UdeM
- [x] @iolyd Évaluer scope du livrable intermédiaire pour le suivi mensuel du mois de mai

# List of actions

- [x] Inviter @AgathePC
- [x] Prendre les notes de rencontre

**Comment by AgathePC** [comment]
Je serai présente à la rencontre.
