### ISSUE TITLE
Task: Rédiger guide d'évaluation des projets et charte de valeurs de la plateforme

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#85]
## Task description

Une fois que les critères d'exemplarité et de qualité des projets sont mieux définis, il faudrait rédiger un guide d'évaluation qui servira entre autre à mettre en évidence les valeurs à promouvoir à travers les fiches publiées sur Nplex.

Plutôt que d'instaurer un système d'évaluation _procédural_, avec une grille de cases à cocher, il est proposé d'adopter une approche plus organique où les éditeurs et utilisateurs qui soumettent des projets ont accès à un guide qui leur présente:

- la philosophie du projet Nplex;
- les valeurs que les projets d'aménagement soumis devraient faire transparaître;
- des questions ou des exemples qui illustrent les valeurs identifiées.

L'approche proposée par la [Boussole Qualité](https://udemontreal-my.sharepoint.com/:b:/g/personal/emmanuel_beaudry_marchand_umontreal_ca/EfxGtDdT7wdDi8ONDjG_tMQBCtonryU5KJ6LzsajeR2emw?e=6mqoSk) nous sert ici de référence sur le plan du cadrage des concepts et de la longueur des énoncés.

Ce travail se décline en deux volets:

1. Rédaction d'un guide
2. Ajustement du guide et du template des projets pour adéquation au niveau des éléments valorisés

Ultimement, nous pouvons aussi réfléchir à l'articulation entre la présentation du guide, l'arborescence des pages de l'application (qui affecte la navigation des utilisateurs), et la saisie de données à un niveau plus fin de UX/UI. Par exemple, le guide pourrait être décomposé et présenté sous forme de _tooltips_ associés à chaque champ de saisie dans le formulaire de soumission de projet.

## Liens

- Ce issue est en lien avec #27
- [Document de travail](https://udemontreal-my.sharepoint.com/:w:/g/personal/emmanuel_beaudry_marchand_umontreal_ca/Eb10mBdOv6dGspMml_sum3oBHswO8ULatFHNykBHHKNhuA?e=szmm6b)
- [Boussole Qualité](https://udemontreal-my.sharepoint.com/:b:/g/personal/emmanuel_beaudry_marchand_umontreal_ca/EfxGtDdT7wdDi8ONDjG_tMQBCtonryU5KJ6LzsajeR2emw?e=6mqoSk)

## Notes

- Trouver une source gouvernementale ou municipale pour l'emplacement des fenêtres

## To do

- [x] Rédiger une version continue
- [x] Identifier des exemples ou des questions qui pourraient aider les lecteurs à appliquer l'évaluation proposée par le guide
- [x] Décomposition du guide sous forme de _tooltips_
- [x] Adapter la rédaction pour intégration web

**Comment by AgathePC** [comment]
@iolyd Quel format devraient prendre les exemples selon toi? Ça pourrait être des vrais projets québécois ou internationaux, avec ou sans photo. Sinon, ça pourrait être une énumération texte d'exemples génériques (ex: présence de toilettes non-genrées, installation de bacs de réutilisation des eaux de pluie, etc.). Finalement, ça pourrait être des liens vers des projets de la plateforme.

**Comment by iolyd** [comment]
@AgathePC , en ce moment je viserais autant que possible des exemples anonymes ou fictifs pour éviter des complications sur le plan éthique, au format texte et/ou illustré (schémas, photos, illustrations artistiques, etc.) selon ce qui s'applique le mieux pour résumer l'idée de manière succinte et claire.
J'aime aussi bien l'idée de lien vers des projets documentés sur la plateforme, mais l'introduction de ce format devra attendre un peu, le temps de cumuler un corpus assez varié de fiches.

**Comment by AgathePC** [comment]
@iolyd J'ai commencé à rédiger les exemples. Dis-moi si tu aimerais qu'on discute de la charte ensemble cette semaine ou la semaine prochaine.

**Comment by AgathePC** [comment]
@iolyd après lecture du formulaire et de son introduction, j'ai ajouté des commentaires dans le document. Dans l'ensemble, le document confirme les catégories et les critères déjà présents dans notre guide.

**Comment by AgathePC** [comment]
@iolyd en faisant une première version des tooltips, je me suis rendu compte que les catégories de la fiche de projet n'étaient pas très solides. J'en ai fait plus que pas assez, en ajoutant des tootips par mots-clés. Je pourrai ajuster le format selon tes commentaires. J'ai également fait une synthèse du guide, que je pense réduire encore un peu.

**Comment by iolyd** [comment]
@AgathePC Je suis en train de passer au travers du tout et ça me semble pas pire. Je me demande si les _tooltips_ devraient être principalement conçus selon les "catégories" de la fiche projet ou plutôt selon les paramètres / choix à l'intérieur de ces catégories. Dans tous les cas, je crois qu'un mélange des deux sera nécessaire pour s'ajuster au niveaux de familiarité et de détail variables des catégories. Autrement, le format de rédaction est très bon, ça me paraît être la bonne longueur et le bon langage pour des notices d'information.

**Comment by AgathePC** [comment]
@iolyd Il m'est difficile d'imaginer comment concevoir les tooltips à partir des _paramètres / choix à l'intérieur des catégories_, puisque, pour la plupart, il s'agit de choix simple comme _matériaux québécois_ ou des échelles de 1 à 5. J'ai cependant corrigé quelques problèmes avec la structure de la fiche de projet que j'avais proposée, ce qui permet en bonus de proposer plus de tooltips. Si je n'ai pas bien compris la tâche, je serai disponible cette semaine pour une rencontre vidéo. 
J'ai également tenté de raccourcir encore la version courte (elle est environ à 1150 mots), mais je ne sais plus quoi retirer ou condenser. Je me demandais également si tu voulais que je produise une liste des éléments à indiquer sur le calendrier des fiches de projet, ou si c'était déjà assez clair dans ta tête?

**Comment by iolyd** [comment]
Au premier abord la version courte me semble assez bonne en terme de contenu, pour la racourcir davantage ça serait probablement une question de condenser la syntaxe générale. Pour l'instant je te propose de la garder comme c'est en longueur et d'y apporter des modifs plus sur le plan du contenu si jamais tu en identifies en travaillant sur d'autres aspects (voir point suivant).

Excellente idée pour le calendrier de la fiche-projet, ça serait effectivement pertinent de lister plus explicitement des types d'événements ou de phases qu'il pourrait contenir. Pour référence quant à la structure des données et une liste très sommaire d'exemples d'événements ou processus, je t'invite à consulter le [modèle de données](https://udemontreal-my.sharepoint.com/:b:/g/personal/emmanuel_beaudry_marchand_umontreal_ca/ESlmIySL9JhCshG_L1Yy1WoB4PmaY-HQXNNGrOSHc-O7hg?e=v2yp9b) préliminaire livré par le CEN-R, aux pages 8 et 11 sur 20 (ou aux endroit où il est question de la table `Event` ou d'éléments connexes). Avec tes connaissance en aménagement, je crois qu'un aspect intéressant serait de clarifier qu'est-ce qu'il serait pertinent d'y retrouver sous forme de processus vs sous forme d'événement ponctuel, et comment certains peuvent s'articuler ensemble ou s'imbriquer. (Par exemple, un processus d'`obtention de permis` pourrait contenir un `dépôt de la demande`, une `réception du permis`, etc.)

**Comment by AgathePC** [comment]
@iolyd j'ai fait un essai pour le calendrier. N'hésite pas à me donner tes commentaires!

**Comment by iolyd** [comment]
@AgathePC Super, c'est excellent comme base. J'ai ajouté mes commentaires, et aussi quelques questions vu que je suis moins familier avec certains aspects des processus en aménagement.

**Comment by iolyd** [comment]
Salut @Sarahprairie, aurais-tu du temps demain ou en début de semaine prochaine pour qu'on discute du guide? Laisse-moi savoir quand ça te conviendrait.

**Comment by Sarahprairie** [comment]
Je suis disponible lundi prochain toute la journée, est-ce qu'il y a une heure qui te convient mieux ?

**Comment by iolyd** [comment]
Re-salut @Sarahprairie, désolé j'ai manqué de temps dans mon horaire hier. Serais-tu disponible ce pm ou demain (excepté 15h30-16h)?

**Comment by Sarahprairie** [comment]
@iolyd, pas de soucis! Je ne suis malheureusement pas disponible demain puisque j'ai des cours, mais je le suis jeudi et vendredi toute la journée. Dis moi quel moment te conviendrait mieux

**Comment by Sarahprairie** [comment]
Parfait, par visio serait plus simple pour moi

**Comment by iolyd** [comment]
Salut @Sarahprairie, pourrait-on faire une rencontre prochainement pour faire un retour sur ta lecture du guide?
