### ISSUE TITLE
Task: Obtenir le guide des bonnes pratiques de AFSQ

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#87]
# Task Description

Tel que discuté lors du dernier rassemblement des projets de la Ville, [Architecture sans frontières](https://www.asf-quebec.org/en/) a développé un guide des bonnes pratiques vis-à-vis les enjeux d'itinérance et d'intégration sociale en architecture/urbanisme. Il serait pertinent de conjuguer certains critères de ce guide avec la charte des valeurs de Nplex.

Notamment, il pourrait y avoir des éléments de réflexion pertinents au niveau du projet des [PAQ](https://www.asf-quebec.org/paq/).

Pour plus d'information, il faudrait entrer en contact avec Maude Ledoux

# List of actions

- [ ] Récupérer le guide de ASFQ
  - [ ] Si nécessaire, contacter l'organisme directement
- [ ] Se familiariser avec le guide de ASFQ
- [ ] Lire sur le projet des PAQ
- [ ] Identifier les éléments intéressants
- [ ] Contacter Maude Ledoux pour plus d'information ou pour des documents spécifiques
