### ISSUE TITLE
Task: (Premier) suivi auprès de JD de la Ville de Montréal

### ISSUE THREAD

**Issue by iolyd** [CUPUM/nplex#98]
# Task Description

Suite au départ de Sylvie, Jacinthe De Guire s'occupera du suivi du projet pour le reste de la collaboration avec la Ville.

La rencontre a lieu mardi le 26 juillet, 13h30.

## Notes

- Charte / guide -> Nommer "Guide de sélection"
- Voir les 2 dimensions de la boussole qualité
- Consulter le [fomulaire de soumission d'étude de cas](https://designmontreal.com/concours/qualite-en-design-et-en-architecture-des-sites-industriels-montrealais) comme inspiration pour le formulaire de soumission des projets de Nplex
- Mettre en valeur comment un projet n'a pas à être exemplaire sur tout les points:
  - Potentiel de développement d'une culture design plus critique, moins axée uniquement sur l'esthétique / la plasticité des résultats

# List of actions
## Préparation et points de discussion
- [x] Bloquer heure au calendrier
- [x] Avancer au maximum bases du UI + features minimum
- [x] Discuter du déroulement des prochaines activités, définition des phases à venir du projet

## Suivis
- [x] Déposer un document/index avec livrables clairs
- [x] #99 
- [x] Vérifier livrables et jalons escomptés dans la convention
  - Selon la planif initiale, il y avait un atelier en juin. Mais aucun "jalon" lié avec un livrable et un paiement outre celui à venir cet automne

**Comment by iolyd** [comment]
Salut @sjinko, en discutant avec JD au sujet des jalons établis dans la convention entre la Ville et la Chaire, nous avons trouvé qu'il serait pertinent de discuter un peu de la description de certaines étapes. Il était notamment question d'un jalon supposément prévu en juin, avec un paiement de la ville, mais celui-ci m'aurait échappé lors de mes lectures de la convention dans le passé. Je n'ai plus accès au document depuis la panne de CIRRUS, l'aurais-tu sur ton ordinateur ou sur onedrive par hasard?

**Comment by sjinko** [comment]
Salut @iolyd, voici le lien GH pour le dossier de subvention: https://github.com/CUPUM/subventions/tree/main/20210414-designmontreal

Je te laisse voir, mais dis-moi si il y a un souci.
